# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gobuster_result.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes\ made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import * 
from PyQt5.QtCore import *
import sys
import time
import threading
from api.sqlmap_api import SQLMap
from api.xsstrike_api import XSStrike
from tinydb_database import DB_connect
# from FYP_GUI import Ui_MainWindow
# from FYP_GUI import Ui_MainWindow
# from gobuster_results_GUI import Ui_MainWindow_Gobuster_Result

# Signal mssgbox
class at_signal_mssgbox(QObject):
    at_signal = pyqtSignal(str)
    
    def __init__(self):
        super().__init__()
        self.at_signal.connect(self.at_check_signal)
        
    def at_check_signal(self,msg):
        if msg == "None_target_url":
            QMessageBox.warning(None, 'Error Message Box', 'Please input the URL and parameter!', QMessageBox.Close)
        elif msg == "None_header":
            QMessageBox.warning(None, 'Error Message Box', 'Please input the Cookie!', QMessageBox.Close)
        elif msg == "DOM":
            QMessageBox.information(None, 'Information Message Box', 'XSStrike DOM vulnerabilities Found!\n Please check attack tools Raw Result', QMessageBox.Close)
            pass
        pass
    pass

#create gobuster result page with PyQt5, clicked = lambda: self.opengoresult()
class Ui_MainWindow_Attack_Tool(object):
    def show_mainwindow(self, MainWindow,SecondWindow):
        MainWindow.show()
        SecondWindow.hide()
        pass
        
    def setupUi(self, SecondWindow, MainWindow):
        SecondWindow.setObjectName("SecondWindow")
        #MainWindow.resize(630, 520)
        SecondWindow.setFixedSize(630, 520)

        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.tabw_main_attack_tool = QtWidgets.QTabWidget(self.centralwidget)
        self.tabw_main_attack_tool.setGeometry(QtCore.QRect(-10, 0, 645, 460))
        self.tabw_main_attack_tool.setObjectName("tabw_main_attack_tool")
        
        self.btn_return_page = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.show_mainwindow(MainWindow, SecondWindow))
        self.btn_return_page.setGeometry(QtCore.QRect(10, 470, 200, 25))
        self.btn_return_page.setObjectName("btn_return_page")
        self.btn_return_page.setToolTip("Go back to Main/Scanning Tool(s) Page")
        # self.btn_return_page.clicked.connect(QtWidgets.qApp.quit)
        # self.btn_next_page.clicked.connect(self.switch_next_page)

        self.tab_tools = QtWidgets.QWidget()
        self.tab_tools.setObjectName("tab_tools")
        
        self.lbl_tools = QtWidgets.QLabel(self.tab_tools)
        self.lbl_tools.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_tools.setFont(font)
        self.lbl_tools.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_tools.setObjectName("lbl_tools")
        
        self.cmb_tool = QtWidgets.QComboBox(self.tab_tools)
        self.cmb_tool.setGeometry(QtCore.QRect(80, 20, 141, 31))
        self.cmb_tool.setObjectName("cmb_tool")
        self.cmb_tool.addItem("")
        self.cmb_tool.addItem("")
        # self.cmb_tool.addItem("")
        self.cmb_tool.activated.connect(self.changes_frame)

        self.lbl_url = QtWidgets.QLabel(self.tab_tools)
        self.lbl_url.setGeometry(QtCore.QRect(10, 60, 70, 30))
        self.lbl_url.setObjectName("lbl_url")

        # self.btn_using_default_url = QtWidgets.QRadioButton(self.tab_tools)
        # self.btn_using_default_url.setGeometry(QtCore.QRect(83, 62, 120, 30))
        # self.btn_using_default_url.setObjectName("btn_using_default_url")
        # self.btn_using_default_url.setText("Use Result List")
        # self.btn_using_default_url.setChecked(True)
        # self.btn_using_default_url.toggled.connect(self.switch_default_user_url)

        self.btn_using_user_url = QtWidgets.QRadioButton(self.tab_tools)
        self.btn_using_user_url.setGeometry(QtCore.QRect(80, 62, 120, 30))
        self.btn_using_user_url.setObjectName("btn_using_user_url")
        self.btn_using_user_url.setText("Use User URL")
        self.btn_using_user_url.setChecked(True)
        self.btn_using_user_url.toggled.connect(self.switch_default_user_url)

        self.btn_using_header_file = QtWidgets.QRadioButton(self.tab_tools)
        self.btn_using_header_file.setGeometry(QtCore.QRect(220, 62, 150, 30))
        self.btn_using_header_file.setObjectName("btn_using_header_file")
        self.btn_using_header_file.setText("Use Header File")
        self.btn_using_header_file.toggled.connect(self.switch_default_user_url)
        self.btn_using_header_file.hide()

        # self.cmb_url = QtWidgets.QComboBox(self.tab_tools)
        # self.cmb_url.setGeometry(QtCore.QRect(30, 100, 240, 31))
        # self.cmb_url.setObjectName("cmb_url")
        # if len(Ui_MainWindow_Gobuster_Result.Gobuster_Result) > 0:
        #     for loop in Ui_MainWindow_Gobuster_Result.Gobuster_Result:
        #         self.cmb_url.addItem(f"{loop}")
        #         pass
        # else:
        #     self.cmb_url.addItem("No record")
        #     pass

        self.txt_target_url = QtWidgets.QLineEdit(self.tab_tools)
        self.txt_target_url.setGeometry(QtCore.QRect(30, 100, 240, 31))
        self.txt_target_url.setObjectName("txt_target_url")
        self.txt_target_url.setToolTip("Input the target url and injection point")
        # self.txt_target_url.hide()

        self.btn_get_header_file = QtWidgets.QPushButton(self.tab_tools)
        self.btn_get_header_file.setGeometry(QtCore.QRect(30, 100, 240, 31))
        self.btn_get_header_file.setText("Select Header File")
        self.btn_get_header_file.hide()
        self.btn_get_header_file.clicked.connect(self.select_header_txt_file)
        
        self.lbl_tool_name = QtWidgets.QLabel(self.tab_tools)
        self.lbl_tool_name.setGeometry(QtCore.QRect(30, 140, 591, 21))
        self.lbl_tool_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_tool_name.setObjectName("lbl_tool_name")
        
        self.at_pb = QtWidgets.QProgressBar(self.tab_tools)
        self.at_pb.setGeometry(QtCore.QRect(30, 135, 581, 21))
        self.at_pb.setRange(0, 0)
        # self.at_pb.move(20,400)
        self.at_pb.setValue(50)
        style = '''
            QProgressBar {
                border: 2px solid #000;
                border-radius: 5px;
                text-align:center;
                height: 20px;
                width:200px;
            }
            QProgressBar::chunk {
                background: #09c;
                width:1px;
            }
        ''' 
        self.at_pb.setStyleSheet(style)
        self.at_pb.hide()
        
        self.frame_tool = QtWidgets.QFrame(self.tab_tools)
        self.frame_tool.setGeometry(QtCore.QRect(30, 160, 581, 260))
        self.frame_tool.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_tool.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tool.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tool.setObjectName("frame_tool")
        
        self.chk_sqlmap_header = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_sqlmap_header.setGeometry(QtCore.QRect(10, 10, 250, 30))
        self.chk_sqlmap_header.setObjectName("chk_sqlmap_header")
        self.chk_sqlmap_header.setText("Cookie (Might not required):")
        self.chk_sqlmap_header.clicked.connect(self.choose_sqlmap_option)
        
        
        self.txt_sqlmap_header = QtWidgets.QLineEdit(self.frame_tool)
        self.txt_sqlmap_header.setGeometry(QtCore.QRect(145, 10, 250, 30))
        self.txt_sqlmap_header.setObjectName("txt_sqlmap_header")
        self.txt_sqlmap_header.setDisabled(True)
        self.txt_sqlmap_header.setToolTip("User might have type the cookie(sessionID) from a request header in the text box to perform the attack!")
        
        self.lbl_sqlmap_level = QtWidgets.QLabel(self.frame_tool)
        self.lbl_sqlmap_level.setGeometry(QtCore.QRect(10, 40, 250, 30))
        self.lbl_sqlmap_level.setObjectName("lbl_sqlmap_level")
        self.lbl_sqlmap_level.setText("Payload Quantity:")

        self.cmb_sqlmap_level = QtWidgets.QComboBox(self.frame_tool)
        self.cmb_sqlmap_level.setGeometry(QtCore.QRect(145, 40, 250, 30))
        self.cmb_sqlmap_level.setObjectName("cmb_sqlmap_level")
        self.cmb_sqlmap_level.addItem("1")
        self.cmb_sqlmap_level.addItem("2")
        self.cmb_sqlmap_level.addItem("3")
        self.cmb_sqlmap_level.addItem("4")
        self.cmb_sqlmap_level.addItem("5")

        self.lbl_sqlmap_risk = QtWidgets.QLabel(self.frame_tool)
        self.lbl_sqlmap_risk.setGeometry(QtCore.QRect(10, 70, 250, 30))
        self.lbl_sqlmap_risk.setObjectName("lbl_sqlmap_risk")
        self.lbl_sqlmap_risk.setText("Payload Strength:")

        self.cmb_sqlmap_risk = QtWidgets.QComboBox(self.frame_tool)
        self.cmb_sqlmap_risk.setGeometry(QtCore.QRect(145, 70, 250, 30))
        self.cmb_sqlmap_risk.setObjectName("cmb_sqlmap_risk")
        self.cmb_sqlmap_risk.addItem("1")
        self.cmb_sqlmap_risk.addItem("2")
        self.cmb_sqlmap_risk.addItem("3")

        self.chk_sqlmap_db_name = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_sqlmap_db_name.setGeometry(QtCore.QRect(10, 100, 135, 30))
        self.chk_sqlmap_db_name.setObjectName("chk_sqlmap_db_name")
        self.chk_sqlmap_db_name.setText("Database name:")
        self.chk_sqlmap_db_name.setDisabled(True)
        self.chk_sqlmap_db_name.clicked.connect(self.choose_sqlmap_option)

        self.cmb_sqlmap_db_name = QtWidgets.QComboBox(self.frame_tool)
        self.cmb_sqlmap_db_name.setGeometry(QtCore.QRect(145, 100, 250, 30))
        self.cmb_sqlmap_db_name.setObjectName("cmb_sqlmap_db_name")
        self.cmb_sqlmap_db_name.setDisabled(True)

        self.chk_sqlmap_table_name = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_sqlmap_table_name.setGeometry(QtCore.QRect(10, 130, 140, 30))
        self.chk_sqlmap_table_name.setObjectName("chk_sqlmap_table_name")
        self.chk_sqlmap_table_name.setText("Tables name:")
        self.chk_sqlmap_table_name.setDisabled(True)
        self.chk_sqlmap_table_name.clicked.connect(self.choose_sqlmap_option)

        self.cmb_sqlmap_table_name = QtWidgets.QComboBox(self.frame_tool)
        self.cmb_sqlmap_table_name.setGeometry(QtCore.QRect(145, 130, 250, 30))
        self.cmb_sqlmap_table_name.setObjectName("cmb_sqlmap_table_name")
        self.cmb_sqlmap_table_name.setDisabled(True)

        self.chk_sqlmap_tables_arg = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_sqlmap_tables_arg.setGeometry(QtCore.QRect(10, 160, 260, 30))
        self.chk_sqlmap_tables_arg.setObjectName("chk_sqlmap_tables_arg")
        self.chk_sqlmap_tables_arg.setText("Display the Database table(s)")
        # self.chk_sqlmap_tables_arg.setChecked(True)
        self.chk_sqlmap_tables_arg.setDisabled(True)

        self.btn_sqlmap_columns_arg = QtWidgets.QRadioButton(self.frame_tool)
        self.btn_sqlmap_columns_arg.setGeometry(QtCore.QRect(10, 190, 260, 30))
        self.btn_sqlmap_columns_arg.setObjectName("btn_sqlmap_columns_arg")
        self.btn_sqlmap_columns_arg.setText("Display the table column(s) information")
        self.btn_sqlmap_columns_arg.setChecked(True)
        self.btn_sqlmap_columns_arg.setDisabled(True)

        self.btn_sqlmap_records_arg = QtWidgets.QRadioButton(self.frame_tool)
        self.btn_sqlmap_records_arg.setGeometry(QtCore.QRect(10, 220, 260, 30))
        self.btn_sqlmap_records_arg.setObjectName("btn_sqlmap_records_arg")
        self.btn_sqlmap_records_arg.setText("Display the table record(s)")
        self.btn_sqlmap_records_arg.setDisabled(True)

        self.chk_xsstrike_header = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_xsstrike_header.setGeometry(QtCore.QRect(10, 10, 250, 30))
        self.chk_xsstrike_header.setObjectName("chk_xsstrike_header")
        self.chk_xsstrike_header.setText("Cookie (Might not required):")
        self.chk_xsstrike_header.hide()
        self.chk_xsstrike_header.clicked.connect(self.choose_xsstrike_option)

        self.txt_xsstrike_header = QtWidgets.QLineEdit(self.frame_tool)
        self.txt_xsstrike_header.setGeometry(QtCore.QRect(145, 10, 250, 30))
        self.txt_xsstrike_header.setObjectName("txt_xsstrike_header")
        self.txt_xsstrike_header.setDisabled(True)
        self.txt_xsstrike_header.hide()
        self.txt_xsstrike_header.setToolTip("User might have type the cookie(sessionID) from a request header in the text box to perform the attack!")
        
        self.chk_xsstrike_fuzzer = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_xsstrike_fuzzer.setGeometry(QtCore.QRect(10, 40, 250, 30))
        self.chk_xsstrike_fuzzer.setObjectName("chk_xsstrike_fuzzer")
        self.chk_xsstrike_fuzzer.setText("fuzzer")
        self.chk_xsstrike_fuzzer.clicked.connect(self.choose_xsstrike_option)
        self.chk_xsstrike_fuzzer.hide()
        self.chk_xsstrike_fuzzer.setToolTip("The fuzzer is meant to test filters and Web Application Firewalls. \nIt is painfully slow because it sends randomly* delay requests and the delay can be up to 30 seconds.")
        
        self.chk_xsstrike_skip_dom = QtWidgets.QCheckBox(self.frame_tool)
        self.chk_xsstrike_skip_dom.setGeometry(QtCore.QRect(10, 70, 250, 30))
        self.chk_xsstrike_skip_dom.setObjectName("chk_xsstrike_skip_dom")
        self.chk_xsstrike_skip_dom.setText("Skip DOM Scanning")
        self.chk_xsstrike_skip_dom.hide()

        self.tabw_main_attack_tool.addTab(self.tab_tools, "")

        self.tab_tool_result = QtWidgets.QWidget()
        self.tab_tool_result.setObjectName("tab_tool_result")
        
        self.lbl_tool = QtWidgets.QLabel(self.tab_tool_result)
        self.lbl_tool.setGeometry(QtCore.QRect(10, 10, 611, 380))
        self.lbl_tool.setObjectName("lbl_tool")
        # Record to Database setting
        self.lbl_select_record_to_db = QtWidgets.QLabel(self.tab_tool_result)
        self.lbl_select_record_to_db.setGeometry(QtCore.QRect(15, 0, 250, 30))
        self.lbl_select_record_to_db.setText("Select record to database mode")

        self.radiobtn_select_db_mode_insert_to_exist_record = QtWidgets.QRadioButton(self.tab_tool_result)
        self.radiobtn_select_db_mode_insert_to_exist_record.setGeometry(QtCore.QRect(15, 25, 160, 30))
        self.radiobtn_select_db_mode_insert_to_exist_record.setText("Insert to Exist Record")
        self.radiobtn_select_db_mode_insert_to_exist_record.toggled.connect(lambda: self.selectbox_insert_to_exist_database.setEnabled(True))

        self.radiobtn_select_db_mode_create_new_record = QtWidgets.QRadioButton(self.tab_tool_result)
        self.radiobtn_select_db_mode_create_new_record.setGeometry(QtCore.QRect(15, 55, 160, 30))
        self.radiobtn_select_db_mode_create_new_record.setText("Create New Record")
        self.radiobtn_select_db_mode_create_new_record.toggled.connect(lambda: self.selectbox_insert_to_exist_database.setEnabled(False))

        self.selectbox_insert_to_exist_database = QtWidgets.QComboBox(self.tab_tool_result)
        self.selectbox_insert_to_exist_database.setGeometry(QtCore.QRect(165, 25, 300, 30))
        self.selectbox_insert_to_exist_database.setEnabled(False)

        #get database list
        db_result= DB_connect.get_all_record_id_datetime_address() #dict 
        exist_database_list = list()
        self.selectbox_insert_to_exist_database.setDisabled(True)
        for item in db_result:
            exist_database_list.append(f"{item['id']} - {item['target_address']}")
        self.selectbox_insert_to_exist_database.clear()
        if len(exist_database_list) != 0:
            self.selectbox_insert_to_exist_database.addItems(exist_database_list)
            self.selectbox_insert_to_exist_database.setDisabled(False)

        # self.btn_create_new_record
        # self.btn_insert_to_exist
        # Record to Database button
        self.btn_result_record_to_db = QtWidgets.QPushButton(self.tab_tool_result)
        self.btn_result_record_to_db.setGeometry(QtCore.QRect(450, 55, 180, 30))
        self.btn_result_record_to_db.setText("Store Result to Record")
        self.btn_result_record_to_db.clicked.connect(self.insert_result_to_db)
        self.btn_result_record_to_db.setDisabled(True)
        # Result table
        self.table_namp = QTableWidget(self.tab_tool_result)
        self.table_namp.setGeometry(QtCore.QRect(10, 90, 620, 340))
        
        self.tabw_main_attack_tool.addTab(self.tab_tool_result, "")

        self.tab_tool_raw = QtWidgets.QWidget()
        self.tab_tool_raw.setObjectName("tab_tool")
        
        self.lbl_raw_result = QtWidgets.QLabel(self.tab_tool_raw)
        self.lbl_raw_result.setObjectName("lbl_raw_result")
        self.lbl_raw_result.setGeometry(QtCore.QRect(10, 10, 620, 10))
        self.lbl_raw_result.setAlignment(QtCore.Qt.AlignTop)
        self.lbl_raw_result.setText("No Scanning Raw Result")
        self.lbl_raw_result.setWordWrap(True)
        
        # create scroll bar for raw result page
        self.at_raw_topFiller = QWidget()
        self.at_raw_topFiller.setMinimumSize(610, 1000)
        self.at_raw_scroll = QScrollArea(self.tab_tool_raw)
        self.at_raw_scroll.setWidget(self.at_raw_topFiller)
        self.at_raw_scroll.setGeometry(0, 0, 635, 460)
        at_raw_layout_result = QVBoxLayout(self.at_raw_topFiller)
        at_raw_layout_result.addWidget(self.lbl_raw_result)

        self.tabw_main_attack_tool.addTab(self.tab_tool_raw, "")
                
        SecondWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        self.tabw_main_attack_tool.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

        self.btn_scan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scan.setGeometry(QtCore.QRect(430, 470, 89, 25))
        self.btn_scan.setObjectName("btn_scan")
        self.btn_scan.setText("Scan")
        self.btn_scan.clicked.connect(self.make_scanning_thread)
        self.btn_scan.setToolTip("Scan the Attack Tool(s)")

        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(530, 470, 89, 25))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_exit.clicked.connect(QApplication.instance().quit)
        self.btn_exit.setText("Exit")
        self.btn_exit.setToolTip("Exit the Page")

        self.btn_scan.raise_()
        self.btn_exit.raise_()

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("MainWindow", "Find Vulnerability Tool"))
        self.lbl_tools.setText(_translate("MainWindow", "Tools:"))
        self.cmb_tool.setItemText(0, _translate("MainWindow", "SQLmap"))
        self.cmb_tool.setItemData(0, "SQLmap for SQL injection", QtCore.Qt.ToolTipRole)
        self.cmb_tool.setItemText(1, _translate("MainWindow", "XSStrike"))
        self.cmb_tool.setItemData(1, "XSStrike for Cross Site Scripting (XSS) injection", QtCore.Qt.ToolTipRole)
        # self.cmb_tool.setItemText(2, _translate("MainWindow", "XXExploiter"))
        self.lbl_url.setText(_translate("MainWindow", "Which url:"))
        
        self.btn_return_page.setText(_translate("MainWindow", "Return to the Previous Page"))
        self.btn_return_page.setFont(QFont('Arial'))
        
        self.lbl_tool_name.setText(_translate("MainWindow", "Config:"))
        self.tabw_main_attack_tool.setTabText(self.tabw_main_attack_tool.indexOf(self.tab_tools), _translate("MainWindow", "Attack Tools"))
        self.lbl_tool.setText(_translate("MainWindow", "No result now"))
        self.tabw_main_attack_tool.setTabText(self.tabw_main_attack_tool.indexOf(self.tab_tool_result), _translate("MainWindow", "Tool Result"))
        self.tabw_main_attack_tool.setTabText(self.tabw_main_attack_tool.indexOf(self.tab_tool_raw), _translate("MainWindow", "Tool Raw"))


    def changes_frame(self):
        if self.cmb_tool.currentText() == "SQLmap":
            self.chk_sqlmap_tables_arg.show()
            self.btn_sqlmap_columns_arg.show()
            self.btn_sqlmap_columns_arg.setChecked(True)
            self.chk_sqlmap_db_name.show()
            self.cmb_sqlmap_db_name.show()
            self.chk_sqlmap_table_name.show()
            self.cmb_sqlmap_table_name.show()
            # self.btn_get_header_file.show()
            # self.btn_using_header_file.show()
            self.btn_using_user_url.setChecked(True)
            self.btn_using_header_file.setChecked(False)
            self.btn_sqlmap_records_arg.show()
            self.lbl_sqlmap_level.show()
            self.cmb_sqlmap_level.show()
            self.lbl_sqlmap_risk.show()
            self.cmb_sqlmap_risk.show()
            self.chk_sqlmap_header.show()
            self.txt_sqlmap_header.show()
            self.chk_xsstrike_header.hide()
            self.txt_xsstrike_header.hide()
            self.chk_xsstrike_fuzzer.hide()
            self.chk_xsstrike_skip_dom.hide()
            pass
        elif self.cmb_tool.currentText() == "XSStrike":
            self.chk_xsstrike_header.show()
            self.txt_xsstrike_header.show()
            self.chk_xsstrike_fuzzer.show()
            self.chk_xsstrike_skip_dom.show()
            self.chk_sqlmap_tables_arg.hide()
            self.btn_sqlmap_columns_arg.hide()
            self.chk_sqlmap_db_name.hide()
            self.cmb_sqlmap_db_name.hide()
            self.chk_sqlmap_table_name.hide()
            self.cmb_sqlmap_table_name.hide()
            self.btn_get_header_file.hide()
            self.btn_using_header_file.hide()
            self.btn_sqlmap_records_arg.hide()
            self.lbl_sqlmap_level.hide()
            self.cmb_sqlmap_level.hide()
            self.lbl_sqlmap_risk.hide()
            self.cmb_sqlmap_risk.hide()
            self.chk_sqlmap_header.hide()
            self.txt_sqlmap_header.hide()
            pass
        else:
            pass
        pass

    def switch_default_user_url(self):
        # if self.btn_using_default_url.isChecked() == True:
        #     self.txt_target_url.hide()
        #     self.btn_get_header_file.hide()
            # self.cmb_url.show()
        if self.btn_using_user_url.isChecked() == True:
            self.btn_get_header_file.hide()
            # self.cmb_url.hide()
            self.txt_target_url.show()
        elif self.btn_using_header_file.isChecked() == True:
            # self.cmb_url.hide()
            self.txt_target_url.hide()
            self.btn_get_header_file.show()
        else:
            pass
        pass

    def make_scanning_thread(self):
        self.at_call_signal = at_signal_mssgbox()
        scan_thread = threading.Thread(target=self.thread_scan)
        scan_thread.start()
        pass

    def thread_scan(self):
        result_raw = ""
        
        # SQLMap Scan
        if self.cmb_tool.currentText() == "SQLmap":
            # Get value
            tables_arg = self.chk_sqlmap_tables_arg.isChecked()
            columns_arg = self.btn_sqlmap_columns_arg.isChecked()
            records_arg = self.btn_sqlmap_records_arg.isChecked()
            db_name = self.cmb_sqlmap_db_name.currentText()
            table_name = self.cmb_sqlmap_table_name.currentText()
            level_arg = self.cmb_sqlmap_level.currentText()
            risk_arg = self.cmb_sqlmap_risk.currentText()
            
            if self.chk_sqlmap_header.isChecked() == False:
                phpSessId = None
            elif self.chk_sqlmap_header.isChecked() == True:
                phpSessId = self.txt_sqlmap_header.text()
                if phpSessId == "":
                    self.at_call_signal.at_signal.emit("None_header")
                    time.sleep(1)
                    return False
            
            self.btn_result_record_to_db.setDisabled(True)
            self.table_namp.clear()

            if self.btn_using_user_url.isChecked() == True:
                injection_point = str(self.txt_target_url.text())
                if injection_point == "":
                    self.at_call_signal.at_signal.emit("None_target_url")
                    time.sleep(1)
                    return False
                
                self.btn_scan.setDisabled(True)
                self.btn_exit.setDisabled(True)
                self.at_pb.show()
                self.lbl_tool_name.hide()
                
                # Call SQLMap API
                if (self.chk_sqlmap_db_name.isChecked() == True) and (self.chk_sqlmap_table_name.isChecked() == True):
                    self.sqlmap_scan = SQLMap(injection_point=injection_point,user_agent="FYP",tables_arg=tables_arg,columns_arg=columns_arg,records_arg=records_arg, level_arg=level_arg, risk_arg=risk_arg, db_name=db_name,table_name=table_name,phpSessId=phpSessId)
                    pass
                elif self.chk_sqlmap_db_name.isChecked() == True:
                    self.sqlmap_scan = SQLMap(injection_point=injection_point,user_agent="FYP",tables_arg=tables_arg,level_arg=level_arg, risk_arg=risk_arg,db_name=db_name,phpSessId=phpSessId)
                else:
                    self.sqlmap_scan = SQLMap(injection_point=injection_point,user_agent="FYP",level_arg=level_arg, risk_arg=risk_arg,phpSessId=phpSessId)
                pass
            # Use Header File 
            # elif self.btn_using_header_file.isChecked() == True:
            #     try:
            #         if self.header_txt_file == "":
            #             QMessageBox.critical(
            #                                 self,
            #                                 'Sorry',
            #                                 'Please select the header txt file!'
            #                         )
            #             return False
            #         injection_point = self.header_txt_file
            #     except:
            #         QMessageBox.critical(
            #                             self,
            #                             'Sorry',
            #                             'Please select the header txt file!'
            #                         )
            #         return False
            #         pass
            #     if (self.chk_sqlmap_db_name.isChecked() == True) and (self.chk_sqlmap_table_name.isChecked() == True):
            #         self.sqlmap_scan = SQLMap(injection_point=injection_point,user_agent="FYP",tables_arg=tables_arg,columns_arg=columns_arg,records_arg=records_arg,level_arg=level_arg, risk_arg=risk_arg,db_name=db_name,table_name=table_name,phpSessId=phpSessId)
            #         pass
            #     elif self.chk_sqlmap_db_name.isChecked() == True:
            #         self.sqlmap_scan = SQLMap(injection_point=injection_point,user_agent="FYP",tables_arg=tables_arg,level_arg=level_arg, risk_arg=risk_arg,db_name=db_name,phpSessId=phpSessId)
            #     else:
            #         self.sqlmap_scan = SQLMap(injection_point=injection_point,user_agent="FYP",level_arg=level_arg, risk_arg=risk_arg,phpSessId=phpSessId)
            #     pass

            #     # self.btn_get_header_file.clicked.connect(self.select_header_txt_file())
                
            #     pass
            # else:
            #     pass
            
            # Start the SQLMap Scan
            self.sqlmap_scan_result = self.sqlmap_scan.sqlmap_get_methon()
            self.sqlmap_scan_filter_result = self.sqlmap_scan.sqlmap_result_filter()

            #Display Raw Result
            for loop in self.sqlmap_scan_result:
                    result_raw += f"{loop}"
                    self.lbl_raw_result.setText(result_raw)
                    self.lbl_raw_result.adjustSize()
                    pass
                
            self.chk_sqlmap_db_name.setDisabled(False)
            self.chk_sqlmap_table_name.setDisabled(False)
            # self.lbl_tool_name.setText("Config:")

            # sqlmap result list arg
            sqlmap_result_arg_temp_dbs_array = 0
            sqlmap_result_arg_temp_dict = 1
            sqlmap_result_arg_tables_temp_array= 2
            sqlmap_result_arg_columns_temp_dict = 3
            sqlmap_result_arg_records_temp_array = 4

            # display database list to combobox
            if len(self.sqlmap_scan_filter_result[sqlmap_result_arg_temp_dbs_array]) != 0:
                self.cmb_sqlmap_db_name.clear()
                self.cmb_sqlmap_db_name.addItems(self.sqlmap_scan_filter_result[sqlmap_result_arg_temp_dbs_array])
                self.btn_result_record_to_db.setDisabled(False)
                
            # display database table list to combobox
            if len(self.sqlmap_scan_filter_result[sqlmap_result_arg_tables_temp_array]) != 0 :  
                self.cmb_sqlmap_table_name.clear()
                self.cmb_sqlmap_table_name.addItems(self.sqlmap_scan_filter_result[sqlmap_result_arg_tables_temp_array])
                self.btn_result_record_to_db.setDisabled(False)

            # diplay sqlmap result to result tab table
            result = ""
            for i in self.sqlmap_scan_filter_result:
                result += f"{i}\n"
                # self.lbl_tool.setText(result)
                print(i)
            if self.chk_sqlmap_table_name.isChecked():
                # diplay sqlmap selected table column information
                if self.btn_sqlmap_columns_arg.isChecked() :

                    temp_list = self.sqlmap_scan_filter_result[sqlmap_result_arg_columns_temp_dict]
                    if len(temp_list) != 0:
                        self.table_namp.setRowCount(len(temp_list))
                        self.table_namp.setColumnCount(2)

                        self.table_namp.setHorizontalHeaderLabels(['Column','DataType'])
                        line = 0
                        for key in temp_list:
                            self.table_namp.setItem(line,0 ,QTableWidgetItem(key) )
                            self.table_namp.setItem(line,1, QTableWidgetItem(temp_list[key]) )
                            line = line + 1
                # diplay sqlmap result selected table record
                elif self.btn_sqlmap_records_arg.isChecked() :
                    temp_list = self.sqlmap_scan_filter_result[sqlmap_result_arg_records_temp_array]
                    if len(temp_list)!=0:
                        self.table_namp.setRowCount(len(temp_list))
                        self.table_namp.setColumnCount(len(temp_list[0]))
                        self.table_namp.setHorizontalHeaderLabels(temp_list[0])
                        record_count = 0
                        for record in temp_list:
                            key_count = 0
                            for key in record:
                                self.table_namp.setItem(record_count,key_count,QTableWidgetItem(record[key]))
                                key_count = key_count + 1
                            record_count = record_count + 1
                    pass

        # XSStrike Scan
        elif self.cmb_tool.currentText() == "XSStrike":
            # Get value
            if self.btn_using_user_url.isChecked() == True:
                target = str(self.txt_target_url.text())
                if target == "":
                    self.at_call_signal.at_signal.emit("None_target_url")
                    time.sleep(1)
                    return False
                
                if self.chk_xsstrike_header.isChecked() == True:
                    headers = str(self.txt_xsstrike_header.text()) 
                    if headers == "":
                        self.at_call_signal.at_signal.emit("None_header")
                        time.sleep(1)
                        return False
                    
                skip_dom = self.chk_xsstrike_skip_dom.isChecked()
                fuzzer_mode = self.chk_xsstrike_fuzzer.isChecked()
                
                self.btn_scan.setDisabled(True)
                self.btn_exit.setDisabled(True)
                self.at_pb.show()
                self.lbl_tool_name.hide()
                
                # Call XSStrike API
                self.xsstrike_scan = XSStrike(target=target, headers=headers, skip_dom=skip_dom, fuzzer_mode=fuzzer_mode, xsstrike_filter_arg=True)
                
                # Start XSStrike Scan
                self.xsstrike_scan_raw_result, self.xsstrike_scan_result_filtered = self.xsstrike_scan.xsstrike_scan()
                print(self.xsstrike_scan_result_filtered)
                
                #Display Raw Result
                for loop in self.xsstrike_scan_raw_result:
                    result_raw += f"{loop}"
                    self.lbl_raw_result.setText(result_raw)
                self.lbl_raw_result.adjustSize()
                
                #Display table result
                if type(self.xsstrike_scan_result_filtered) == list :#fuzzer
                    self.btn_result_record_to_db.setDisabled(False)
                    # print(f"filtered: {self.xsstrike_scan_result_filtered}")
                    self.table_namp.setRowCount(len(self.xsstrike_scan_result_filtered))
                    self.table_namp.setColumnCount(1)
                    self.table_namp.setHorizontalHeaderLabels(['possible payload'])
                    row = 0
                    for data in self.xsstrike_scan_result_filtered:
                        self.table_namp.setItem(row,0,QTableWidgetItem(data))
                        row = row + 1
                    self.table_namp.setColumnWidth(0,800)

                elif type(self.xsstrike_scan_result_filtered) == dict:# Payload/ DOM and Paylosd
                    if self.xsstrike_scan_result_filtered["DOM"] == True:
                        self.at_call_signal.at_signal.emit("DOM")
                        pass
                    if self.xsstrike_scan_result_filtered["Payload"] != "May not provide payload": #return database
                        
                        pass
                    pass
        else:
            pass
        
        self.lbl_raw_result.adjustSize()
        self.at_raw_topFiller.adjustSize()
        self.btn_scan.setDisabled(False)
        self.btn_exit.setDisabled(False)
        self.lbl_tool_name.show()
        self.at_pb.hide()
        pass

        

    def insert_result_to_db(self):
        # print('test')     
        if self.cmb_tool.currentText() == "SQLmap":
            target_url = self.txt_target_url.text()
            database_name = self.cmb_sqlmap_db_name.currentText()
            table_name = self.cmb_sqlmap_table_name.currentText()
            payload_quantity=self.cmb_sqlmap_level.currentText()
            payload_strength=self.cmb_sqlmap_risk.currentText()
            if self.btn_sqlmap_columns_arg.isChecked() :
                datatype = "columns"
                temp_list = self.sqlmap_scan_filter_result[3]
            if self.btn_sqlmap_records_arg.isChecked():
                datatype = "record"
                temp_list = self.sqlmap_scan_filter_result[4]

            data = {"tools":'sqlmap',
                    "target_url":target_url,
                    "database":database_name,
                    "table":table_name,
                    "datatype":datatype,
                    "payload_quantity":payload_quantity,
                    "payload_strength":payload_strength,
                    "result":temp_list}
            
        elif self.cmb_tool.currentText() == "XSStrike":
            target_url = self.txt_target_url.text()
            if self.chk_xsstrike_header.isChecked():
                cookie_info = self.txt_xsstrike_header.text()
            else:
                cookie_info = False

            # for testing
            # result = ['<test', '<test//', '<test>', '<test x>', '<test x=y', '<test x=y//', '<test/oNxX=yYy//', '<test oNxX=yYy>', '<test onload=x', '<test/o%00nload=x', '<test sRc=xxx', '<test data=asa', '<test data=javascript:asa', '<svg x=y>', '<details x=y//', '<a href=x//', '<emBed x=y>', '<object x=y//', '<bGsOund sRc=x>', '<iSinDEx x=y//', '<aUdio x=y>', '<script x=y>', '<script//src=//', '">payload<br/attr="', '"-confirm``-"', '<test ONdBlcLicK=x>', '<test/oNcoNTeXtMenU=x>', '<test OndRAgOvEr=x>']
            data = {"tools":'xsstrike',
                    "target_url":target_url,
                    "cookie_info":cookie_info,
                    "result": self.xsstrike_scan_result_filtered
                    }
            
            pass   

        # print(data)
        if data:
            if self.radiobtn_select_db_mode_insert_to_exist_record.isChecked() == True:
                select_database_text = self.selectbox_insert_to_exist_database.currentText()
                select_database_id = select_database_text.split(" - ",1)
                try:
                    db_id = int(select_database_id[0])
                except:
                    print("attack_tools internal Error")
                pass
            elif self.radiobtn_select_db_mode_create_new_record.isChecked() == True:
                db_id = DB_connect.insert_new_event(domain=target_url)
                self.selectbox_insert_to_exist_database.addItem(f"{db_id} - {target_url}")
                pass
            status = DB_connect.insert_tools_receivedData(id=db_id,receivedData=data)
            
    def choose_sqlmap_option(self):
        #checkbox db nmae option setting
        if self.chk_sqlmap_header.isChecked() == True:
            self.txt_sqlmap_header.setDisabled(False)
        elif self.chk_sqlmap_header.isChecked() == False:
            self.txt_sqlmap_header.setDisabled(True)
        
        if self.chk_sqlmap_table_name.isChecked() == True:
            self.cmb_sqlmap_table_name.setDisabled(False)
            self.cmb_sqlmap_db_name.setDisabled(False)
            self.chk_sqlmap_db_name.setChecked(True)
            self.chk_sqlmap_db_name.setDisabled(True)
            self.btn_sqlmap_columns_arg.setDisabled(False)
            self.btn_sqlmap_records_arg.setDisabled(False)
            # self.cmb_sqlmap_db_name.setDisabled(False)
        elif self.chk_sqlmap_table_name.isChecked() == False:
            self.cmb_sqlmap_table_name.setDisabled(True)
            self.cmb_sqlmap_db_name.setDisabled(True)
            # self.chk_sqlmap_db_name.setChecked(False)
            self.chk_sqlmap_db_name.setDisabled(False)
            # self.cmb_sqlmap_db_name.setDisabled(True)
            self.btn_sqlmap_columns_arg.setDisabled(True)
            self.btn_sqlmap_records_arg.setDisabled(True)

        #checkbox db nmae option setting
        if self.chk_sqlmap_db_name.isChecked() == True:
            self.cmb_sqlmap_db_name.setDisabled(False)
            self.chk_sqlmap_tables_arg.setDisabled(False)
            if (self.chk_sqlmap_table_name.isChecked() == True):
                self.chk_sqlmap_tables_arg.setDisabled(True)
                self.chk_sqlmap_tables_arg.setChecked(False)
        elif self.chk_sqlmap_db_name.isChecked() == False:
            self.cmb_sqlmap_db_name.setDisabled(True)
            self.chk_sqlmap_tables_arg.setDisabled(True)
            
        if self.cmb_sqlmap_db_name.count() == 0:
            self.chk_sqlmap_db_name.setDisabled(True)
            
        if self.cmb_sqlmap_table_name.count() == 0:
            self.chk_sqlmap_table_name.setDisabled(True)
        pass

    def choose_xsstrike_option(self):
        if self.chk_xsstrike_header.isChecked() == True:
            self.txt_xsstrike_header.setDisabled(False)
            pass
        elif self.chk_xsstrike_header.isChecked() == False:
            self.txt_xsstrike_header.setDisabled(True)
            
        if self.chk_xsstrike_fuzzer.isChecked() == True:
            self.chk_xsstrike_skip_dom.setChecked(True)
            self.chk_xsstrike_skip_dom.setDisabled(True)
            pass
        elif self.chk_xsstrike_fuzzer.isChecked() == False:
            self.chk_xsstrike_skip_dom.setDisabled(False)
            pass
        pass

    def select_header_txt_file(self):
        dialog = QFileDialog()
        dialog.setFileMode(QFileDialog.AnyFile)
        dialog.setFilter(QDir.Files)
        dialog.setNameFilter("*.txt")

        if dialog.exec_():
            self.header_txt_file  = dialog.selectedFiles()
            if type(self.header_txt_file) == list and len(self.header_txt_file) == 1:
                if self.header_txt_file[0].endswith(".txt"):
                    self.header_txt_file = self.header_txt_file[0]
                    return True 
                else:
                    QMessageBox.critical(
                                        self,
                                        'Error',
                                        'only allow import one txt file!'
                                    )
                    return False          
        else:
            return False
        
if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Attack_Tool()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
