# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FYP_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import threading
import sys
import tools
import os
import time
import pprint
import queue
from gobuster_results_GUI import Ui_MainWindow_Gobuster_Result
from attack_tools_GUI import Ui_MainWindow_Attack_Tool
from gobuster_filter_list_editer_GUI import UI_gobuster_filter_list_editer
from extension_GUI import UI_extension_management
from tinydb_database import DB_connect

# Signal mssgbox
class signal_mssgbox(QObject):
    signal = pyqtSignal(str,int)
    return_nmap_user_select:str = None
    return_gobuster_user_select:str = None
    
    def __init__(self):
        super().__init__()
        self.signal.connect(self.check_signal)
        
    def check_signal(self,check_parameter,db_id):
        if check_parameter == "Done_wait_Nikto": #nikto not ok
            QMessageBox.information(MainWindow, 'Information Message Box', 'Nmap, Whatweb and Gobuster Scanning is finished', QMessageBox.Close)
        elif check_parameter == "Done":
            # Display Successful msgbox #all ok
            QMessageBox.information(MainWindow, 'Information Message Box', 'Scanning is finished', QMessageBox.Close)
        elif check_parameter == "nmap_port":
            # Ask User choose port
            namp_record_port_list = []
            nmap_records = DB_connect.get_one_tool_result(id=db_id,tool_name="nmap")
            for record in nmap_records:
                if record.get("target_address", None) != None and record.get("portid", None) != None:
                    namp_record_port_list.append(record['portid'])
            selected_portid, ok_btn = QInputDialog.getItem(MainWindow,'please select targer server portid', 'portid:',namp_record_port_list,0,False)
            if ok_btn:
                for record in nmap_records:
                    if record.get("portid",None) == selected_portid:
                        selected_target_address = record['target_address']
                signal_mssgbox.return_nmap_user_select = selected_target_address
                return selected_target_address
            else:
                signal_mssgbox.return_nmap_user_select = nmap_records[0]['target_address']
                return nmap_records[0]['target_address']
        elif check_parameter == "Gobuster_wordlist":
            user_reply = QMessageBox.question(MainWindow, "Question", "Do you want to choose the wordlist?", QMessageBox.Yes | QMessageBox.No)
            whatweb_status = False
            # #Get whatweb recommend wordlist 
            whatweb_recommend_wordlist = DB_connect.get_one_tool_result(id=db_id,tool_name="whatweb")
            num_of_whatweb_result = len(whatweb_recommend_wordlist)
            if num_of_whatweb_result > 0: 
                whatweb_status = True
                wordlist = whatweb_recommend_wordlist[0]['wordlist']
                
            if user_reply == QMessageBox.Yes:# ask user select wordlist
                wordlist_dict = {'wordpress':f"{os.path.dirname(__file__)}/Wordlists/CMS/wordpress.txt",
                                 'drupal':f"{os.path.dirname(__file__)}/Wordlists/CMS/drupal.txt",
                                 'common':f"{os.path.dirname(__file__)}/Wordlists/common.txt"}
                wordlist_name = wordlist_dict.keys()
                
                seleced_key, ok_btn = QInputDialog.getItem(MainWindow,'please select wordlist', 'wordlist:',wordlist_name,0,False)
                if ok_btn:
                    signal_mssgbox.return_gobuster_user_select = wordlist_dict[seleced_key]#User choose wordlist
                    return wordlist_dict[seleced_key]
                else:
                    if whatweb_status == True: # if whatweb have result
                        signal_mssgbox.return_gobuster_user_select = wordlist#By Default wordlist
                        return wordlist
                    else: # if whatweb no result
                        signal_mssgbox.return_gobuster_user_select = f"{os.path.dirname(__file__)}/Wordlists/common.txt" #By Default wordlist
                        return f"{os.path.dirname(__file__)}/Wordlists/common.txt"
            else: #if NO
                if whatweb_status == True: # if whatweb have result
                    signal_mssgbox.return_gobuster_user_select = wordlist#By Default wordlist
                    return wordlist
                else: # if whatweb no result
                    signal_mssgbox.return_gobuster_user_select = f"{os.path.dirname(__file__)}/Wordlists/common.txt" #By Default wordlist
                    return f"{os.path.dirname(__file__)}/Wordlists/common.txt"
        elif check_parameter == "Gobuster_dir":
            QMessageBox.information(MainWindow, 'Information Message Box', 'If you think the results of directory scan might contain other contents,\n you can take that directory to scan again (on Gobuster only).', QMessageBox.Close)
            pass
        pass

    pass
#create GUI with PyQt5
class Ui_MainWindow(object):
    SHOW_ATTACK_GUI = 0

    def setupUi(self, MainWindow):
        
        #create the hole GUI basic setting(size, color, etc)
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(630, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setFixedSize(630, 520)

        self.tabw_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabw_main.setGeometry(QtCore.QRect(-10, 0, 645, 460))
        self.tabw_main.setMaximumSize(QtCore.QSize(651, 16777215))
        self.tabw_main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabw_main.setObjectName("tabw_main")

        #create Home page 
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        # self.tab_home.setToolTip("Main Page")

        #create input target label(name) 
        self.lbl_target = QtWidgets.QLabel(self.tab_home)
        self.lbl_target.setGeometry(QtCore.QRect(70, 240, 53, 21))
        self.lbl_target.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_target.setObjectName("lbl_target")

        #create input target area
        self.txt_target = QtWidgets.QLineEdit(self.tab_home)
        self.txt_target.setGeometry(QtCore.QRect(130, 240, 431, 25))
        self.txt_target.setObjectName("txt_target")
        self.txt_target.setToolTip("IP/URL is target server network address and directory")

        #create input User-agent label(name) 
        self.lbl_user_agent = QtWidgets.QLabel(self.tab_home)
        self.lbl_user_agent.setGeometry(QtCore.QRect(50, 280, 75, 21))
        self.lbl_user_agent.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_user_agent.setObjectName("lbl_user_agent")

        #create User-agent ComboBox
        self.cmb_user_agent = QtWidgets.QComboBox(self.tab_home)
        self.cmb_user_agent.setGeometry(QtCore.QRect(130, 280, 431, 25))
        self.cmb_user_agent.setObjectName("cmb_user_agent")

        #create Default mode box
        self.chk_dmode = QtWidgets.QCheckBox(self.tab_home)
        self.chk_dmode.setGeometry(QtCore.QRect(490, 350, 111, 23))
        self.chk_dmode.setObjectName("chk_dmode")
        self.chk_dmode.setChecked(True)
        self.chk_dmode.clicked.connect(self.set_by_default)
        

        #create Welcome message and color
        self.lbl_welcome1 = QtWidgets.QLabel(self.tab_home)
        self.lbl_welcome1.setGeometry(QtCore.QRect(76, 100, 520, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.lbl_welcome1.setFont(font)
        self.lbl_welcome1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_welcome1.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.lbl_welcome1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_welcome1.setObjectName("lbl_welcome1")
        
        
        self.lbl_welcome2 = QtWidgets.QLabel(self.tab_home)
        self.lbl_welcome2.setGeometry(QtCore.QRect(80, 150, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lbl_welcome2.setFont(font)
        self.lbl_welcome2.setStyleSheet("color: rgb(98, 144, 164)\n"
"")
        self.lbl_welcome2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_welcome2.setObjectName("lbl_welcome2")
        
        #create Setting page after Home page 
        self.tabw_main.addTab(self.tab_home, "")
        
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        # self.tab_setting.setToolTip("Config Scanning Tool Page")
        
        self.setting_tabWidget = QtWidgets.QTabWidget(self.tab_setting)
        self.setting_tabWidget.setGeometry(QtCore.QRect(0, 0, 640, 440))
        self.setting_tabWidget.setObjectName("setting_tabWidget")

        #In Setting page create Nmap page for user to change setting
        self.nmap_tab = QtWidgets.QWidget()
        self.nmap_tab.setObjectName("nmap_tab")
        # self.nmap_tab.setToolTip("Nmap Setting Page")
        
        self.lbl_nmap = QtWidgets.QLabel(self.nmap_tab)
        self.lbl_nmap.setGeometry(QtCore.QRect(10, 0, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_nmap.setFont(font)
        self.lbl_nmap.setObjectName("lbl_nmap")

        #radio button for nmap default setting
        self.btn_nmap_default = QtWidgets.QRadioButton(self.nmap_tab)
        self.btn_nmap_default.setGeometry(QtCore.QRect(80, 40, 310, 23))
        self.btn_nmap_default.setObjectName("btn_nmap_default")
        self.btn_nmap_default.setChecked(True)
        self.btn_nmap_default.setDisabled(True)
        
        #checkbox for nmap_run setting
        self.chk_nmap_run = QtWidgets.QCheckBox(self.nmap_tab)
        self.chk_nmap_run.setGeometry(QtCore.QRect(20, 40, 50, 23))
        self.chk_nmap_run.setObjectName("chk_nmap_run")
        self.chk_nmap_run.setChecked(True)
        self.chk_nmap_run.setDisabled(True)

        #make a frame to include the different nmap setting check box
        self.frame_nmap = QtWidgets.QFrame(self.nmap_tab)
        self.frame_nmap.setGeometry(QtCore.QRect(10, 70, 621, 321))
        self.frame_nmap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_nmap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_nmap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_nmap.setObjectName("frame_nmap")
        self.frame_nmap.setDisabled(True)
        
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_nmap)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 20, 511, 40))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.setChecked(True)
        
        self.setting_tabWidget.addTab(self.nmap_tab, "")
        
        #create whatweb setting page(only default mode can use)
        self.tab_whatweb = QtWidgets.QWidget()
        self.tab_whatweb.setObjectName("tab_whatweb")
        # self.tab_whatweb.setToolTip("Whatweb Setting Page")
        
        self.lbl_whatweb = QtWidgets.QLabel(self.tab_whatweb)
        self.lbl_whatweb.setGeometry(QtCore.QRect(10, 0, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_whatweb.setFont(font)
        self.lbl_whatweb.setObjectName("lbl_whatweb")
        
        self.btn_whatweb_default = QtWidgets.QRadioButton(self.tab_whatweb)
        self.btn_whatweb_default.setGeometry(QtCore.QRect(80, 40, 310, 23))
        self.btn_whatweb_default.setObjectName("btn_whatweb_default")
        self.btn_whatweb_default.setEnabled(False)

        #checkbox for whatweb_run setting
        self.chk_whatweb_run = QtWidgets.QCheckBox(self.tab_whatweb)
        self.chk_whatweb_run.setGeometry(QtCore.QRect(20, 40, 50, 23))
        self.chk_whatweb_run.setObjectName("chk_whatweb_run")
        self.chk_whatweb_run.setChecked(True)
        self.chk_whatweb_run.setDisabled(True)
        
        self.frame_whatweb = QtWidgets.QFrame(self.tab_whatweb)
        self.frame_whatweb.setGeometry(QtCore.QRect(10, 70, 621, 321))
        self.frame_whatweb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_whatweb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_whatweb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_whatweb.setObjectName("frame_whatweb")
        self.frame_whatweb.setEnabled(False)
        
        self.chk_whatweb_option = QtWidgets.QCheckBox(self.frame_whatweb)
        self.chk_whatweb_option.setGeometry(QtCore.QRect(10, 10, 500, 51))
        self.chk_whatweb_option.setObjectName("chk_whatweb_option")
        self.chk_whatweb_option.setChecked(True)
        self.chk_whatweb_option.setText("")
        self.chk_whatweb_option.setDisabled(True)

        self.setting_tabWidget.addTab(self.tab_whatweb, "")

        #create gobuster setting page include default and 3 different setting by radio button
        self.tab_gobuster = QtWidgets.QWidget()
        self.tab_gobuster.setObjectName("tab_gobuster")
        # self.tab_gobuster.setToolTip("Gobuster Setting Page")
        
        self.lbl_gobuster = QtWidgets.QLabel(self.tab_gobuster)
        self.lbl_gobuster.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_gobuster.setFont(font)
        self.lbl_gobuster.setObjectName("lbl_gobuster")
        
        self.btn_gobuster_default = QtWidgets.QRadioButton(self.tab_gobuster)
        self.btn_gobuster_default.setGeometry(QtCore.QRect(80, 40, 120, 23))
        self.btn_gobuster_default.setObjectName("btn_gobuster_default")
        self.btn_gobuster_default.setChecked(True)
        self.btn_gobuster_default.setDisabled(True)
        self.btn_gobuster_default.clicked.connect(self.set_by_default_gobuster)
        
        #checkbox for gobuster_run setting
        self.chk_gobuster_run = QtWidgets.QCheckBox(self.tab_gobuster)
        self.chk_gobuster_run.setGeometry(QtCore.QRect(20, 40, 50, 23))
        self.chk_gobuster_run.setObjectName("chk_gobuster_run")
        self.chk_gobuster_run.setChecked(True)
        self.chk_gobuster_run.setDisabled(True)
        
        self.frame_gobuster = QtWidgets.QFrame(self.tab_gobuster)
        self.frame_gobuster.setGeometry(QtCore.QRect(10, 70, 621, 321))
        self.frame_gobuster.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_gobuster.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_gobuster.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_gobuster.setObjectName("frame_gobuster")
        self.frame_gobuster.setDisabled(True)
        
        #button for gobuster choose the different mode
        self.btn_gobuster_mode_vhost = QtWidgets.QRadioButton(self.frame_gobuster)
        self.btn_gobuster_mode_vhost.setGeometry(QtCore.QRect(10, 10, 391, 23))
        self.btn_gobuster_mode_vhost.setObjectName("radioButton_10")
        self.btn_gobuster_mode_vhost.clicked.connect()
        
        self.btn_gobuster_mode_subdomain = QtWidgets.QRadioButton(self.frame_gobuster)
        self.btn_gobuster_mode_subdomain.setGeometry(QtCore.QRect(10, 40, 591, 23))
        self.btn_gobuster_mode_subdomain.setObjectName("radioButton_11")
        self.btn_gobuster_mode_dir.clicked.connect()
        
        self.btn_gobuster_mode_dir = QtWidgets.QRadioButton(self.frame_gobuster)
        self.btn_gobuster_mode_dir.setGeometry(QtCore.QRect(10, 70, 391, 23))
        self.btn_gobuster_mode_dir.setObjectName("radioButton_12")
        self.btn_gobuster_mode_dir.setChecked(True)
        self.btn_gobuster_mode_vhost.clicked.connect()
        
        # self.lbl_wordlist = QtWidgets.QLabel(self.frame_gobuster)
        # self.lbl_wordlist.setGeometry(QtCore.QRect(10, 200, 30, 23))
        # self.lbl_wordlist.setObjectName("lbl_wordlist")

        self.btn_gobuster_dir_wordlist_filter = QtWidgets.QPushButton(self.tab_gobuster)
        self.btn_gobuster_dir_wordlist_filter.setGeometry(QtCore.QRect(300, 0, 180, 23))
        self.btn_gobuster_dir_wordlist_filter.setText("Result Filter List Editer")
        self.btn_gobuster_dir_wordlist_filter.clicked.connect(self.gobuster_filter_editer)
        self.btn_gobuster_dir_wordlist_filter.setToolTip("User can filter keyword for directory scanning")

        
        
        self.setting_tabWidget.addTab(self.tab_gobuster, "")
        
        #create Nikto setting page
        self.tab_nikto = QtWidgets.QWidget()
        self.tab_nikto.setObjectName("tab_Nikto")
        # self.tab_nikto.setToolTip("Nikto Setting Page")
        
        self.lbl_nikto = QtWidgets.QLabel(self.tab_nikto)
        self.lbl_nikto.setGeometry(QtCore.QRect(10, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_nikto.setFont(font)
        self.lbl_nikto.setObjectName("lbl_nikto")
        
        self.btn_nikto_default = QtWidgets.QRadioButton(self.tab_nikto)
        self.btn_nikto_default.setGeometry(QtCore.QRect(80, 40, 310, 23))
        self.btn_nikto_default.setObjectName("btn_whatweb_default")
        self.btn_nikto_default.setEnabled(False)
        
         #checkbox for nikto_run setting
        self.chk_nikto_run = QtWidgets.QCheckBox(self.tab_nikto)
        self.chk_nikto_run.setGeometry(QtCore.QRect(20, 40, 50, 23))
        self.chk_nikto_run.setObjectName("chk_nikto_run")
        self.chk_nikto_run.setChecked(True)
        self.chk_nikto_run.setDisabled(True)

        self.frame_nikto = QtWidgets.QFrame(self.tab_nikto)
        self.frame_nikto.setGeometry(QtCore.QRect(10, 70, 621, 321))
        self.frame_nikto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_nikto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_nikto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_nikto.setObjectName("frame_nikto")
        self.frame_nikto.setEnabled(False)
        
        self.chk_nikto_option = QtWidgets.QCheckBox(self.frame_nikto)
        self.chk_nikto_option.setGeometry(QtCore.QRect(10, 10, 470, 51))
        self.chk_nikto_option.setObjectName("chk_nikto_option")
        self.chk_nikto_option.setChecked(True)
        self.chk_nikto_option.setText("")
        self.chk_nikto_option.setDisabled(True)

        self.setting_tabWidget.addTab(self.tab_nikto, "")   
             
        self.tabw_main.addTab(self.tab_setting, "")
        
        #Create the tab for display the scanning state
        self.scan_status = QtWidgets.QWidget()
        self.scan_status.setStyleSheet("")
        self.scan_status.setObjectName("scan_status")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        
        self.scan_status_Layout_namp_0 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.scan_status_Layout_namp_0.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_namp_0.setObjectName("scan_status_Layout_namp_0")
        
        self.lbl_scan_status_nmap = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_scan_status_nmap.setStyleSheet("background-color: rgb(40, 120, 255);")
        self.lbl_scan_status_nmap.setObjectName("lbl_scan_status_nmap")
        self.lbl_scan_status_nmap.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_namp_0.addWidget(self.lbl_scan_status_nmap, 0, 0, 1, 1)
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(160, 0, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        
        self.scan_status_Layout_whatweb_0 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.scan_status_Layout_whatweb_0.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_whatweb_0.setObjectName("scan_status_Layout_whatweb_0")
        
        self.lbl_scan_status_whatweb = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_scan_status_whatweb.setStyleSheet("background-color: rgb(40, 120, 255);")
        self.lbl_scan_status_whatweb.setObjectName("lbl_scan_status_whatweb")
        self.lbl_scan_status_whatweb.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_whatweb_0.addWidget(self.lbl_scan_status_whatweb, 0, 0, 1, 1)
        
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(320, 0, 160, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        
        self.scan_status_Layout_gobuster_0 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.scan_status_Layout_gobuster_0.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_gobuster_0.setObjectName("scan_status_Layout_gobuster_0")
        
        self.lbl_scan_status_gobuster = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_scan_status_gobuster.setStyleSheet("background-color: rgb(40, 120, 255);")
        self.lbl_scan_status_gobuster.setObjectName("lbl_scan_status_gobuster")
        self.lbl_scan_status_gobuster.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_gobuster_0.addWidget(self.lbl_scan_status_gobuster, 0, 0, 1, 1)
        
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(480, 0, 160, 80))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        
        self.scan_status_Layout_Nikto_0 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.scan_status_Layout_Nikto_0.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_Nikto_0.setObjectName("scan_status_Layout_Nikto_0")
        
        self.lbl_scan_status_nikto = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lbl_scan_status_nikto.setStyleSheet("background-color: rgb(40, 120, 255);\n"
"")
        self.lbl_scan_status_nikto.setObjectName("lbl_scan_status_nikto")
        self.lbl_scan_status_nikto.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_Nikto_0.addWidget(self.lbl_scan_status_nikto, 0, 0, 1, 1)
        
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 80, 160, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        
        self.scan_status_Layout_nmap_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.scan_status_Layout_nmap_1.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_nmap_1.setObjectName("scan_status_Layout_nmap_1")
        
        self.lbl_scan_status_nmap_var = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.lbl_scan_status_nmap_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_nmap_var.setObjectName("lbl_scan_status_nmap_var")
        self.lbl_scan_status_nmap_var.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_nmap_1.addWidget(self.lbl_scan_status_nmap_var, 0, 0, 1, 1)
        
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(160, 80, 160, 80))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        
        self.scan_status_Layout_nmap_whatweb_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.scan_status_Layout_nmap_whatweb_1.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_nmap_whatweb_1.setObjectName("scan_status_Layout_nmap_whatweb_1")
        
        self.lbl_scan_status_whatweb_var = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.lbl_scan_status_whatweb_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_whatweb_var.setObjectName("lbl_scan_status_whatweb_var")
        self.lbl_scan_status_whatweb_var.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_nmap_whatweb_1.addWidget(self.lbl_scan_status_whatweb_var, 0, 0, 1, 1)
        
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(320, 80, 160, 80))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        
        self.scan_status_Layout_gobuster_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.scan_status_Layout_gobuster_1.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_gobuster_1.setObjectName("scan_status_Layout_gobuster_1")
        
        self.lbl_scan_status_gobuster_var = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.lbl_scan_status_gobuster_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_gobuster_var.setObjectName("lbl_scan_status_gobuster_var")
        self.lbl_scan_status_gobuster_var.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_gobuster_1.addWidget(self.lbl_scan_status_gobuster_var, 0, 0, 1, 1)
        
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.scan_status)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(480, 80, 160, 80))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        
        self.scan_status_Layout_nikto_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.scan_status_Layout_nikto_1.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_nikto_1.setObjectName("scan_status_Layout_nikto_1")
        
        self.lbl_scan_status_nikto_var = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.lbl_scan_status_nikto_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_nikto_var.setObjectName("lbl_scan_status_nikto_var")
        self.lbl_scan_status_nikto_var.setAlignment(QtCore.Qt.AlignCenter)
        
        self.scan_status_Layout_nikto_1.addWidget(self.lbl_scan_status_nikto_var, 0, 0, 1, 1)
        
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scan_status)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 641, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        
        #create ProgressBar whilte loading
        self.pb = QtWidgets.QProgressBar(self.scan_status)
        self.pb.setGeometry(QtCore.QRect(20, 430, 590, 21))
        self.pb.setRange(0, 0)
        self.pb.move(20,400)
        self.pb.setValue(50)
        style = '''
            QProgressBar {
                border: 2px solid #000;
                border-radius: 5px;
                text-align:center;
                height: 20px;
                width:200px;
            }
            QProgressBar::chunk {
                background: #09c;
                width:1px;
            }
        ''' 
        self.pb.setStyleSheet(style)
        self.pb.hide()
        
        self.scan_status_Layout_statusbar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.scan_status_Layout_statusbar.setContentsMargins(0, 0, 0, 0)
        self.scan_status_Layout_statusbar.setObjectName("scan_status_Layout_statusbar")
        
        self.tabw_main.addTab(self.scan_status,"")
        
        #create result page
        self.tab_result_raw = QtWidgets.QWidget()
        self.tab_result_raw.setObjectName("tab_result_raw")
        # self.tab_result_raw.setToolTip("Display All Scanning Tool Raw Result Page")
        
        self.lbl_result_raw = QtWidgets.QLabel(self.tab_result_raw)
        self.lbl_result_raw.setObjectName("lbl_result_raw")
        self.lbl_result_raw.setGeometry(QtCore.QRect(10, 10, 620, 10))
        self.lbl_result_raw.setAlignment(QtCore.Qt.AlignTop)
        self.lbl_result_raw.setWordWrap(True)
        
        self.lbl_result_raw_nikto  = QtWidgets.QLabel(self.tab_result_raw)
        self.lbl_result_raw_nikto.setObjectName("lbl_result_raw_nikto")
        self.lbl_result_raw_nikto.setGeometry(QtCore.QRect(10, 20, 620, 10))
        self.lbl_result_raw_nikto.setAlignment(QtCore.Qt.AlignTop)
        self.lbl_result_raw_nikto.setWordWrap(True)
        
        # create scroll bar for raw result page
        self.raw_topFiller = QWidget()
        self.raw_topFiller.setMinimumSize(610, 1000)
        self.raw_scroll = QScrollArea(self.tab_result_raw)
        self.raw_scroll.setWidget(self.raw_topFiller)
        self.raw_scroll.setGeometry(0, 0, 635, 460)
        raw_layout_result = QVBoxLayout(self.raw_topFiller)
        raw_layout_result.addWidget(self.lbl_result_raw)
        raw_layout_result.addWidget(self.lbl_result_raw_nikto)
        
        self.tabw_main.addTab(self.tab_result_raw, "")
        
        #create targets list page
        self.tab_target_server_list = QtWidgets.QWidget()
        self.tab_target_server_list.setObjectName("tab_targets")
        
        self.lbl_target_list_page = QtWidgets.QLabel(self.tab_target_server_list)
        self.lbl_target_list_page.setText("Select URL to Display Result")
        self.lbl_target_list_page.setStyleSheet("color: blue;")
        self.lbl_target_list_page.setGeometry(QtCore.QRect(50,125,200,40))
        self.lbl_target_list_page.setFont(QFont('Arial', 16))
        
        #target list page selectbox
        self.server_url_list = []
        self.cmb_server_url_list = QtWidgets.QComboBox(self.tab_target_server_list)
        self.cmb_server_url_list.setGeometry(QtCore.QRect(50, 180, 431, 25))
        self.cmb_server_url_list.setObjectName("cmb_server_url_list")
        self.cmb_server_url_list.setStyleSheet("QComboBox"
                                     "{"
                                     "background-color: rgb(51,255,51);"
                                     "font: 14px"
                                     "}")
        #go result page button
        self.btn_go_db_result_page = QtWidgets.QPushButton(self.tab_target_server_list, clicked = lambda: self.go_db_result_page())
        self.btn_go_db_result_page.setGeometry(QtCore.QRect(500, 180, 100, 25))
        self.btn_go_db_result_page.setText("Display")
        self.btn_go_db_result_page.setDisabled(True)
        
        #create Raw page
        self.tab_raw = QtWidgets.QWidget()
        self.tab_raw.setObjectName("tab_raw")
        
        # self.lbl_raw = QtWidgets.QLabel(self.tab_raw)
        # self.lbl_raw.setGeometry(QtCore.QRect(20, 10, 611, 380))
        # self.lbl_raw.setObjectName("lbl_raw")
        # self.lbl_raw.setAlignment(QtCore.Qt.AlignTop)
        # self.lbl_raw.setWordWrap(True)
        
        self.tab_db = QtWidgets.QWidget()
        self.tab_db.setObjectName("tab_db")
        # self.tab_db.setToolTip("Display All Tool Scanning Result Or Result History Page")
        
        self.lbl_id=QtWidgets.QLabel(self.tab_db)
        self.lbl_id.setGeometry(QtCore.QRect(25, 5, 125, 27))
        self.lbl_id.setText("id:")
        self.lbl_id_var=QtWidgets.QLabel(self.tab_db)
        self.lbl_id_var.setGeometry(QtCore.QRect(50, 5, 125, 27))
        self.lbl_Domain = QtWidgets.QLabel(self.tab_db)
        self.lbl_Domain.setGeometry(QtCore.QRect(25, 30, 125, 27))
        self.lbl_Domain.setText("Target Domain:")
        self.lbl_Domain_var = QtWidgets.QLabel(self.tab_db)
        self.lbl_Domain_var.setGeometry(QtCore.QRect(120, 30, 200, 25))

        self.lbl_datetime = QtWidgets.QLabel(self.tab_db)
        self.lbl_datetime.setGeometry(QtCore.QRect(25, 55, 70, 30)) 
        self.lbl_datetime.setText("Datetime:")
        self.lbl_datetime_var = QtWidgets.QLabel(self.tab_db)
        self.lbl_datetime_var.setGeometry(QtCore.QRect(95,55,200,30))

        # self.lbl_user_agnet = QtWidgets.QLabel(self.tab_db)
        # self.lbl_user_agnet.setGeometry(QtCore.QRect(25, 80, 75, 30)) 
        # self.lbl_user_agnet.setText("User agnet:")


        self.result_tab = QtWidgets.QTabWidget(self.tab_db)
        self.result_tab.setGeometry(QtCore.QRect(25,110,590,270))

        ##Tools config Page
        self.result_tab_tools_config = QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_tools_config,"Tools Config")
        self.lbl_result_tools_config_title= QtWidgets.QLabel(self.result_tab_tools_config)
        self.lbl_result_tools_config_title.setGeometry(QtCore.QRect(10, 10, 200, 25))
        self.lbl_result_tools_config_title.setText("Tools Config Page")
        self.lbl_result_tools_config_title.setFont(QFont('Arial', 15))
        self.table_result_tools_config_info = QtWidgets.QTableWidget(self.result_tab_tools_config)
        self.table_result_tools_config_info.setGeometry(QtCore.QRect(10,40,560,190))
        self.table_result_tools_config_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        # self.result_tab.setTabEnabled(0, False)

        ##Nmap Page
        self.result_tab_namp = QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_namp,"Nmap")
        self.result_tab.setTabEnabled(1,False)
        self.lbl_result_namp_title= QtWidgets.QLabel(self.result_tab_namp)
        self.lbl_result_namp_title.setGeometry(QtCore.QRect(10, 10, 200, 25))
        self.lbl_result_namp_title.setText("Nmap Result Page")
        self.lbl_result_namp_title.setFont(QFont('Arial', 15))
        self.table_result_namp_info = QtWidgets.QTableWidget(self.result_tab_namp)
        self.table_result_namp_info.setGeometry(QtCore.QRect(10,40,560,190))
        self.table_result_namp_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        ##Whatweb Page
        self.result_tab_whatweb = QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_whatweb,"Whatweb")
        self.result_tab.setTabEnabled(2,False)
        self.lbl_result_whatweb_title= QtWidgets.QLabel(self.result_tab_whatweb)
        self.lbl_result_whatweb_title.setGeometry(QtCore.QRect(10, 10, 200, 25))
        self.lbl_result_whatweb_title.setText("Whatweb Result Page")
        self.lbl_result_whatweb_title.setFont(QFont('Arial', 15))

        self.result_cmb_whatweb_url = QtWidgets.QComboBox(self.result_tab_whatweb)
        self.result_cmb_whatweb_url.setGeometry(QtCore.QRect(10,40,420,30))
        self.result_btn_whatweb_display = QtWidgets.QPushButton(self.result_tab_whatweb)
        self.result_btn_whatweb_display.setGeometry((QtCore.QRect(450,40,120,30)))
        self.result_btn_whatweb_display.setText("Display")
        #fix lable
        self.result_lbl_whatweb_target_url= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_target_url.setGeometry(QtCore.QRect(10, 80, 100, 25))
        self.result_lbl_whatweb_target_url.setText("Target URL:")
        self.result_lbl_whatweb_web_server= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_web_server.setGeometry(QtCore.QRect(10, 110, 100, 25))
        self.result_lbl_whatweb_web_server.setText("Web Server:")
        self.result_lbl_whatweb_OS= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_OS.setGeometry(QtCore.QRect(10, 140, 170, 25))
        self.result_lbl_whatweb_OS.setText("Server Operating System:")
        self.result_lbl_whatweb_web_technology= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_web_technology.setGeometry(QtCore.QRect(10, 170, 170, 25))
        self.result_lbl_whatweb_web_technology.setText("Web Technology:")
        #dym lable
        self.result_lbl_whatweb_target_url_var= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_target_url_var.setGeometry(QtCore.QRect(90, 80, 500, 25))
        self.result_lbl_whatweb_web_server_var= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_web_server_var.setGeometry(QtCore.QRect(90, 110, 500, 25))
        self.result_lbl_whatweb_OS_var= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_OS_var.setGeometry(QtCore.QRect(170, 140, 170, 25))
        self.result_lbl_whatweb_web_technology_var= QtWidgets.QLabel(self.result_tab_whatweb)
        self.result_lbl_whatweb_web_technology_var.setGeometry(QtCore.QRect(120, 170, 170, 25))


        ##Gobuster Page
        self.result_tab_gobuster= QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_gobuster,"Gobuster")
        self.result_tab.setTabEnabled(3,False)
        self.result_lbl_gobuster_title= QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_title.setGeometry(QtCore.QRect(10, 10, 180, 25))
        self.result_lbl_gobuster_title.setText("Nmap Result Page")
        self.result_lbl_gobuster_title.setFont(QFont('Arial', 15))

        self.result_lbl_gobuster_mode= QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_mode.setGeometry(QtCore.QRect(10, 30, 180, 25))
        self.result_lbl_gobuster_mode.setText("Mode:")
        
        self.result_lbl_gobuster_mode_var= QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_mode_var.setGeometry(QtCore.QRect(50, 30, 180, 25))
        # self.result_lbl_gobuster_mode_var.setText("Mode:")

        self.result_lbl_gobuster_wordlist = QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_wordlist.setGeometry(QtCore.QRect(10, 60, 180, 25))
        self.result_lbl_gobuster_wordlist.setText("Used Wordlist Path:")
        self.result_lbl_gobuster_wordlist_var = QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_wordlist_var.setGeometry(QtCore.QRect(10, 85, 580, 25))

        self.result_lbl_gobuster_dir_result_len = QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_dir_result_len.setGeometry(QtCore.QRect(10, 120, 180, 25))
        self.result_lbl_gobuster_dir_result_len.setText("Directory found:")
        self.result_lbl_gobuster_dir_result_len.hide()
        self.result_lbl_gobuster_dir_result_len_var = QtWidgets.QLabel(self.result_tab_gobuster)
        self.result_lbl_gobuster_dir_result_len_var.setGeometry(QtCore.QRect(110, 120, 580, 25))
        self.result_lbl_gobuster_dir_result_len_var.setText("11")
        self.result_lbl_gobuster_dir_result_len_var.hide()

        self.result_btn_gobuster_open_page = QtWidgets.QPushButton(self.result_tab_gobuster)
        self.result_btn_gobuster_open_page.setGeometry(QtCore.QRect(25, 170, 540, 25))
        self.result_btn_gobuster_open_page.setText("Open new page to view directory result")
        

        self.result_table_gobuster = QtWidgets.QTableWidget(self.result_tab_gobuster)
        self.result_table_gobuster.setGeometry(QtCore.QRect(10, 120, 560, 100))
        self.result_table_gobuster.hide()

        ## Nikto Page
        self.result_tab_nikto= QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_nikto,"Nikto")
        self.result_tab.setTabEnabled(4,False)
        self.result_lbl_nikto_titile = QtWidgets.QLabel(self.result_tab_nikto)
        self.result_lbl_nikto_titile.setGeometry(QtCore.QRect(10, 10, 300, 30))
        self.result_lbl_nikto_titile.setText("Nikto Page")
        self.result_lbl_nikto_titile.setFont(QFont('Arial', 15))
        self.result_Nikto_chk_raw = QtWidgets.QCheckBox(self.result_tab_nikto)
        self.result_Nikto_chk_raw.setGeometry(QtCore.QRect(460, 10, 180, 25))
        self.result_Nikto_chk_raw.setText("Raw Result")
        self.result_Nikto_chk_raw.stateChanged.connect(self.update_result_nikto_table)
        self.result_Nikto_table = QtWidgets.QTableWidget(self.result_tab_nikto)
        self.result_Nikto_table.setGeometry(QtCore.QRect(10, 40, 560, 190))
        self.result_Nikto_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        ## Sqlmap page
        self.result_tab_sqlmap= QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_sqlmap,"Sqlmap")
        self.result_tab.setTabEnabled(5,False)
        # self.result_lbl_sqlmap_titile = QtWidgets.QLabel(self.result_tab_sqlmap)
        # self.result_lbl_sqlmap_titile.setGeometry(QtCore.QRect(10, 10, 560, 30))
        # self.result_lbl_sqlmap_titile.setText("SQLmap Page")
        # self.result_lbl_sqlmap_titile.setFont(QFont('Arial', 15))

        self.result_cmb_sqlmap = QtWidgets.QComboBox(self.result_tab_sqlmap)
        self.result_cmb_sqlmap.setGeometry(QtCore.QRect(10, 3, 560, 30))
        self.result_sqlmap_btn_search = QtWidgets.QPushButton(self.result_tab_sqlmap)
        self.result_sqlmap_btn_search.setGeometry(QtCore.QRect(10, 40, 560, 25))
        self.result_sqlmap_btn_search.setText("show selected result")
        self.result_sqlmap_btn_search.clicked.connect(self.result_sqlmap_table_update)
        self.result_sqlmap_table = QtWidgets.QTableWidget(self.result_tab_sqlmap)
        self.result_sqlmap_table.setGeometry(QtCore.QRect(10, 70, 560, 150))

        ## xsstrike Page
        self.result_tab_xsstrike = QtWidgets.QWidget()
        self.result_tab.addTab(self.result_tab_xsstrike,"XSStrike")
        self.result_tab.setTabEnabled(6,False)

        self.cmb_xsstrike_event_select = QtWidgets.QComboBox(self.result_tab_xsstrike)
        self.cmb_xsstrike_event_select.setGeometry(QtCore.QRect(10,10,420,20))
        self.btn_xsstrike_select = QtWidgets.QPushButton(self.result_tab_xsstrike)
        self.btn_xsstrike_select.setGeometry(450,10,120,30)
        self.btn_xsstrike_select.setText("Search")
        self.btn_xsstrike_select.setStyleSheet(("QComboBox"
                                     "{"
                                     "font: bold 12px"
                                     "}"))

        self.lbl_xsstrike_cookie_info = QtWidgets.QLabel(self.result_tab_xsstrike)
        self.lbl_xsstrike_cookie_info.setGeometry(QtCore.QRect(10,40,80,30))
        self.lbl_xsstrike_cookie_info.setText("Cookie Info:")
        self.lbl_xsstrike_cookie_info_var = QtWidgets.QLabel(self.result_tab_xsstrike)
        self.lbl_xsstrike_cookie_info_var.setGeometry(QtCore.QRect(90,40,480,30))
        self.lbl_xsstrike_cookie_info_var.setText("")

        self.table_xsstrike = QtWidgets.QTableWidget(self.result_tab_xsstrike)
        self.table_xsstrike.setGeometry(QtCore.QRect(10,70,560,160))
        self.table_xsstrike.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)




        self.cmb_db = QtWidgets.QComboBox(self.tab_db)
        self.cmb_db.setGeometry(QtCore.QRect(20, 390, 450, 25))
        self.cmb_db.setObjectName("cmb_db")
        self.cmb_db.setStyleSheet(("QComboBox"
                                     "{"
                                     "background-color: rgb(153,255,);"
                                     "font: bold 12px"
                                     "}"))
        self.cmb_db.setToolTip("Select record history")
        
        self.btn_db_search = QtWidgets.QPushButton(self.tab_db)
        self.btn_db_search.setGeometry(QtCore.QRect(530, 390, 89, 25))
        self.btn_db_search.setObjectName("btn_db_search")
        self.btn_db_search.setDisabled(True)
        self.btn_db_search.clicked.connect(self.result_search_btn_fuct)
        self.btn_db_search.setToolTip("Search the record history")
        
        self.tabw_main.addTab(self.tab_db, "")
        
        self.tab_report = QtWidgets.QWidget()
        self.tab_report.setObjectName("tab_report")
        # self.tab_report.setToolTip("Report Page")
        
        self.lbl_report = QtWidgets.QLabel(self.tab_report)
        self.lbl_report.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.lbl_report.setObjectName("lbl_report")

        # self.tabw_main.addTab(self.tab_report, "")

        self.btn_next_page = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.show_secwindow())
        self.btn_next_page.setGeometry(QtCore.QRect(10, 470, 89, 25))
        self.btn_next_page.setObjectName("btn_next_page")
        self.btn_next_page.setToolTip("Go to Attack Tool(s) Page")
        #self.btn_next_page.clicked.connect(self.switch_next_page)

        self.btn_extension = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.extension())
        self.btn_extension.setGeometry(QtCore.QRect(110, 470, 89, 25))
        self.btn_extension.setObjectName("Extension")
        self.btn_extension.setToolTip("user can import their own script into our tool can run it")

        self.btn_scan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_scan.setGeometry(QtCore.QRect(430, 470, 89, 25))
        self.btn_scan.setObjectName("btn_scan")
        self.btn_scan.clicked.connect(self.call_tool)
        self.btn_scan.setToolTip("Scan the Scanning Tool(s)")

        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(530, 470, 89, 25))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_exit.clicked.connect(QApplication.instance().quit)
        self.btn_exit.setToolTip("Exit the Page")
        
        self.btn_nmap_choose_url_port = QtWidgets.QPushButton()
        self.btn_nmap_choose_url_port.setObjectName("btn_nmap_choose_url_port")
        self.cmb_nmap_choose_url_port = QtWidgets.QComboBox()
        self.cmb_nmap_choose_url_port.setObjectName("cmb_nmap_choose_url_port")

        self.btn_next_page.raise_() 
        self.btn_extension.raise_()
        self.btn_scan.raise_()
        self.btn_exit.raise_()
        self.tabw_main.raise_()

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabw_main.setCurrentIndex(0)
        self.setting_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        
        MainWindow.setWindowTitle(_translate("MainWindow", "Scanning Tool"))
        
        self.lbl_target.setText(_translate("MainWindow", "<strong> IP/URL:</strong>"))
        self.lbl_target.setFont(QFont('Arial', 10))
        
        self.lbl_user_agent.setText(_translate("MainWindow", "<strong> User Agent:</strong>"))
        self.lbl_user_agent.setFont(QFont('Arial', 10))

        self.cmb_user_agent.addItems(["FYP tools", 
                                      "Safari",
                                      "Firefox",
                                      "Gecko",
                                      "Ramdom Normal Browser"])
        self.cmb_user_agent.setCurrentIndex(0)
        self.cmb_user_agent.setStyleSheet("QComboBox"
                                     "{"
                                     "background-color: rgb(255,143,0);"
                                     "font: bold 14px"
                                     "}")
        self.cmb_user_agent.setToolTip("User-Agent header is a characteristic string that lets servers and network peers identify the application \nThis setting will force Goubster, Whatweb, Nikto")

        # self.chk_smode.setText(_translate("MainWindow", "Stealth mode"))
        self.chk_dmode.setText(_translate("MainWindow", "By Default"))
        self.chk_dmode.setFont(QFont('Arial', 10))
        self.chk_dmode.setToolTip("use default all scanning tools configuration")
        
        self.lbl_welcome1.setText(_translate("MainWindow", "<strong>Pentest software integration for web security</strong>"))
        self.lbl_welcome2.setText(_translate("MainWindow", "Thanks for using this <strong>software</strong>"))
        
        self.tabw_main.setTabText(self.tabw_main.indexOf(self.tab_home), _translate("MainWindow", "Home"))
        self.tabw_main.tabBarClicked.connect(self.update_cmb_db)
        self.lbl_nmap.setText(_translate("MainWindow", "Nmap"))
        self.lbl_nmap.setFont(QFont('Arial', 22))
        self.btn_nmap_default.setText(_translate("MainWindow", "By Default(No need config this tool)"))
        self.chk_nmap_run.setText(_translate("MainWindow", "Run"))
        
        self.checkBox_3.setText(_translate("MainWindow", "To get the extra information like OS information, finding version, do the script scanningand traceroute.\nIt also provides many valuable information about target."))
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.nmap_tab), _translate("MainWindow", "Nmap"))
        
        self.lbl_whatweb.setText(_translate("MainWindow", "Whatweb"))
        self.btn_whatweb_default.setText(_translate("MainWindow", "By Default(No need config this tool)"))
        self.chk_whatweb_run.setText(_translate("MainWindow", "Run"))
        self.chk_whatweb_option.setText(_translate("MainWindow", "By default, WhatWeb main use to identify CMS platform and Web Server"))
        
        # self.label_13.setText(_translate("MainWindow", "Do not need to config"))
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.tab_whatweb), _translate("MainWindow", "Whatweb"))
        self.btn_whatweb_default.setEnabled(False)
        self.btn_whatweb_default.setChecked(True)
        
        self.lbl_nikto.setText(_translate("MainWindow", "Nikto"))
        self.btn_nikto_default.setText(_translate("MainWindow", "By Default(No need config this tool)"))
        self.chk_nikto_run.setText(_translate("MainWindow", "Run"))
        self.chk_nikto_option.setText(_translate("MainWindow", "By default, Nikto is used to scan a Web-Server for the vulnerability that can be exploited and \ncan compromise the server "))
        
        # self.label_14.setText(_translate("MainWindow", "Do not need to config"))
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.tab_nikto), _translate("MainWindow", "Nikto"))
        self.btn_nikto_default.setEnabled(False)
        self.btn_nikto_default.setChecked(True)
        
        self.lbl_gobuster.setText(_translate("MainWindow", "Gobuster"))
        self.btn_gobuster_default.setText(_translate("MainWindow", "By Default"))
        self.chk_gobuster_run.setText(_translate("MainWindow", "Run"))
        self.btn_gobuster_mode_vhost.setText(_translate("MainWindow", "To find subdomains in a specific domain (vhost)"))#vhost
        self.btn_gobuster_mode_subdomain.setText(_translate("MainWindow", "To find subdoamin of a domain")) #subdomain 
        self.btn_gobuster_mode_dir.setText(_translate("MainWindow", "To find the directories and files")) #dir
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.tab_gobuster), _translate("MainWindow", "Gobuster"))
        
        self.tabw_main.setTabText(self.tabw_main.indexOf(self.tab_setting), _translate("MainWindow", "Setting"))
        
        # self.lbl_raw.setText(_translate("MainWindow", "No result now"))
        
        self.lbl_scan_status_nmap.setText(_translate("MainWindow", "Nmap"))
        self.lbl_scan_status_whatweb.setText(_translate("MainWindow", "Whatweb"))
        self.lbl_scan_status_gobuster.setText(_translate("MainWindow", "Gobuster"))
        self.lbl_scan_status_nikto.setText(_translate("MainWindow", "Nikto"))
        self.lbl_scan_status_nmap_var.setText(_translate("MainWindow", "Disable"))
        self.lbl_scan_status_whatweb_var.setText(_translate("MainWindow", "Disable"))
        self.lbl_scan_status_gobuster_var.setText(_translate("MainWindow", "Disable"))
        self.lbl_scan_status_nikto_var.setText(_translate("MainWindow", "Disable"))
        self.tabw_main.setTabText(self.tabw_main.indexOf(self.scan_status), _translate("MainWindow", "Scanning Status"))

        self.tabw_main.setTabText(self.tabw_main.indexOf(self.tab_result_raw), _translate("MainWindow", "Raw Result"))
        
        self.btn_db_search.setText(_translate("MainWindow", "Search"))
        self.tabw_main.setTabText(self.tabw_main.indexOf(self.tab_db), _translate("MainWindow", "Result"))

        
        self.lbl_report.setText(_translate("MainWindow", "TextLabel"))
        self.tabw_main.setTabText(self.tabw_main.indexOf(self.tab_report), _translate("MainWindow", "Report"))
        self.btn_next_page.setText(_translate("MainWindow", "Next Page"))
        self.btn_extension.setText(_translate("MainWindow", "Extension"))
        self.btn_scan.setText(_translate("MainWindow", "Scan"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))

    #button call starting scan function
    def call_tool(self):
        if self.txt_target.text() == "":
            #Error Msg Box
            QMessageBox.warning(MainWindow, 'Error Message Box', 'You must input a IP/URL into the target box!', QMessageBox.Close)
            return False
        
        self.call_signal = signal_mssgbox()
        
        #Do the thread for scanning
        thread_scan = threading.Thread(target=self.start_tool_scan)
        thread_scan.start()
        self.tabw_main.setCurrentIndex(2)
        pass

    #Use the thread to start scanning
    def start_tool_scan(self):
        
        # Show the Loading bar
        self.pb.show()
        self.btn_scan.setDisabled(True)
        self.btn_gobuster_dir_wordlist_filter.setDisabled(True)
        self.btn_exit.setDisabled(True)
        # Check User config setting 
        self.config = {
            'Nmap':{"open":0} ,
            'WhatWeb':{"open":0},
            'Gobuster':{"open":0,"mode":"dir"},
            'Nikto':{"open":0}
            }
        
        # Reset the scanning state
        self.lbl_scan_status_nmap_var.setText("Disable")
        self.lbl_scan_status_whatweb_var.setText("Disable")
        self.lbl_scan_status_gobuster_var.setText("Disable")
        self.lbl_scan_status_nikto_var.setText("Disable")
        
        self.lbl_scan_status_nmap_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_whatweb_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_gobuster_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        self.lbl_scan_status_nikto_var.setStyleSheet("background-color: rgb(46, 218, 255);")
        
        # Set the Default mode setting
        if self.chk_dmode.isChecked() == True:
            self.config = {
                'Nmap':{"open":1} ,
                'WhatWeb':{"open":1},
                'Gobuster':{"open":1,"mode":"dir"},
                'Nikto':{"open":1}
                }
        # set the user setting
        elif self.chk_dmode.isChecked() == False:
            if self.chk_nmap_run.isChecked() == True:
                self.config['Nmap'] = {"open":1}
            if self.chk_whatweb_run.isChecked() == True:
                self.config['WhatWeb'] = {"open":1}
            if self.chk_gobuster_run.isChecked() == True:
                self.config['Gobuster'] = {"open":1}
                if self.btn_gobuster_mode_dir.isChecked() == True:
                    self.config['Gobuster'] = {"open":1,"mode":"dir"}
                elif self.btn_gobuster_mode_subdomain.isChecked() == True:
                    self.config['Gobuster'] = {"open":1,"mode":"subdomain"}
                elif self.btn_gobuster_mode_vhost.isChecked() == True:
                    self.config['Gobuster'] = {"open":1,"mode":"vhost"}
            if self.chk_nikto_run.isChecked() == True:
                self.config['Nikto'] = {"open":1}
                pass
            pass

        # Do Scanning(Nmap, Gobuster, Whatweb, Nikto)
        self.list_raw_scan_result = list()
        
        self.scan = tools.Scan(url=self.txt_target.text(), tools_config=self.config, user_agent=self.switch_user_agnet())
        
        self.scan.main()
        self.current_DB_id = self.scan.get_current_DB_id()
        
        #Nmap Scan
        if self.config['Nmap']['open'] == 1:
            self.lbl_scan_status_nmap_var.setText("Scanning...")
            self.lbl_scan_status_nmap_var.setStyleSheet("background-color: rgb(255, 0, 0);")
            
            #start the nmap scan
            self.nmap_raw_result = self.scan.tools_nmap()
            
            pprint_raw_result = pprint.pformat(self.nmap_raw_result)
            lines_raw_result = pprint_raw_result.splitlines()
            text = '\n'.join(pprint_raw_result.splitlines())
            self.list_raw_scan_result.append(text)
                
            # Display the raw result 
            self.display_raw_result_in_lbl_result_raw()
            
            
            self.lbl_scan_status_nmap_var.setText("Scanning Completed!!!")
            self.lbl_scan_status_nmap_var.setStyleSheet("background-color: rgb(0, 255, 0);")
            self.height_setting()

            self.nmap_scan_all_result = DB_connect.get_one_tool_result(id=self.current_DB_id,tool_name="nmap")
            all_port_target_address_list = []    
            
            for record in self.nmap_scan_all_result:
                try:
                    all_port_target_address_list.append(record["target_address"])
                except:
                    pass
            
            # User choose Port
            if len(self.nmap_scan_all_result) > 1:
                self.call_signal.signal.emit("nmap_port",self.current_DB_id)
                time.sleep(1)
                while signal_mssgbox.return_nmap_user_select not in all_port_target_address_list:
                    time.sleep(2)
                    pass
                else:
                    nmap_list = [{'url': signal_mssgbox.return_nmap_user_select}]
                    self.scan.choose_nmap_web_server_dict_list(nmap_list)
                    pass
                    

        elif self.config['Nmap']['open'] == 0:
            self.scan.tools_nmap()
            pass
        
        #Thread Nikto Scan
        thread_nikto = threading.Thread(target=self.thread_nikto_scan)
        thread_nikto.start()
        
        #Whatweb Scan
        if self.config['WhatWeb']['open'] == 1:
            self.lbl_scan_status_whatweb_var.setText("Scanning...")
            self.lbl_scan_status_whatweb_var.setStyleSheet("background-color: rgb(255, 0, 0);")
            
            # Start the whatweb scan
            self.whatweb_raw_result = self.scan.tools_whatweb()
            
            # Set the raw resulrt label and scroll bar height number
            for loop in self.whatweb_raw_result:
                self.list_raw_scan_result.append(loop)
            
            # Display the raw result    
            self.display_raw_result_in_lbl_result_raw()
            
            self.lbl_scan_status_whatweb_var.setText("Scanning Completed!!!")
            self.lbl_scan_status_whatweb_var.setStyleSheet("background-color: rgb(0, 255, 0);")
            self.height_setting()
            
            pass
        elif self.config['WhatWeb']['open'] == 0:
            self.scan.tools_whatweb()
            pass
        
        #Gobuster Scan
        if self.config['Gobuster']['open'] == 1:
            if self.config['Gobuster']['mode'] == "dir":
                self.call_signal.signal.emit("Gobuster_wordlist",self.current_DB_id)
                time.sleep(1)
                while signal_mssgbox.return_gobuster_user_select is None:
                    time.sleep(2)
                else:
                    self.scan.choose_gobuster_dir_wordlist(signal_mssgbox.return_gobuster_user_select)
                    pass
            
            self.lbl_scan_status_gobuster_var.setText("Scanning...")
            self.lbl_scan_status_gobuster_var.setStyleSheet("background-color: rgb(255, 0, 0);")
            
            # Start the gobuster scan
            self.gobuster_result_list, self.gobuster_raw_result = self.scan.tools_gobuster()
            
            if self.config['Gobuster']['mode'] == "dir":
                self.call_signal.signal.emit("Gobuster_dir",self.current_DB_id)
            
            # Set the raw resulrt label and scroll bar height number
            for loop in self.gobuster_raw_result:
                self.list_raw_scan_result.append(loop)
                
            # Display the raw result
            self.display_raw_result_in_lbl_result_raw()
            
            self.lbl_scan_status_gobuster_var.setText("Scanning Completed!!!")
            self.lbl_scan_status_gobuster_var.setStyleSheet("background-color: rgb(0, 255, 0);")
            
            pass
        elif self.config['Gobuster']['open'] == 0:
            self.scan.tools_gobuster()
            pass
        pass
        
        self.btn_scan.setDisabled(False)
        self.btn_gobuster_dir_wordlist_filter.setDisabled(False)
        self.btn_exit.setDisabled(False)
        self.height_setting()
        self.pb.hide()
        if self.lbl_scan_status_nikto_var.text() == "Scanning...":
            self.call_signal.signal.emit("Done_wait_Nikto",self.current_DB_id)
        else:
            self.call_signal.signal.emit("Done",self.current_DB_id)
        pass
    
    def thread_nikto_scan(self):
        #Nikto Scan
        if self.config['Nikto']['open'] == 1:
            self.lbl_scan_status_nikto_var.setText("Scanning...")
            self.lbl_scan_status_nikto_var.setStyleSheet("background-color: rgb(255, 0, 0);")
            
            self.nikto_raw_result = self.scan.tools_nikto()
            
            # Display Nikto raw result in the label lbl_result_raw_nikto
            result = ""
            for loop in self.nikto_raw_result:
                result += f"{loop}"
                self.lbl_result_raw_nikto.setText(result)
            pass
            
            self.lbl_scan_status_nikto_var.setText("Scanning Completed!!!")
            self.lbl_scan_status_nikto_var.setStyleSheet("background-color: rgb(0, 255, 0);")
            self.height_setting()
        
    
    # Set the raw resulrt label and scroll bar height
    def height_setting(self):
        self.lbl_result_raw.adjustSize()
        self.lbl_result_raw_nikto.adjustSize()
        self.raw_topFiller.adjustSize()
            
    # Display Nmap, Whatweb and Gobuster raw result in the label lbl_result_raw
    def display_raw_result_in_lbl_result_raw(self):
        result = ""
        for loop in self.list_raw_scan_result:
                result += f"{loop}\n"
                self.lbl_result_raw.setText(result)
        pass
        
    def insert_item_to_btn_cmb_server_url_list(self,item):
        self.server_url_list.append(item)
        self.cmb_server_url_list.clear()
        self.cmb_server_url_list.addItems(self.server_url_list)
        self.btn_go_db_result_page.setDisabled(False)
        return True
    
    def go_db_result_page(self,database_id="",url:str=""):
        if database_id == "":
            database_id = self.scan.get_current_database_id()
        url = self.cmb_server_url_list.currentText()
        print("hello",database_id,url)
        pass

    def opengofilterlistediter(self):
        self.gobuster_filter_list_editer = QtWidgets.QMainWindow()
        self.ui = UI_gobuster_filter_list_editer()
        self.ui.show()

    def opengoresult(self):
        self.window_gobuster_result = QtWidgets.QMainWindow()
        for key in self.gobuster_result_list:
            self.key = key
        self.ui = Ui_MainWindow_Gobuster_Result(list = self.gobuster_result_list[self.key])
        self.ui.setupUi(self.window_gobuster_result)
        self.ui.disaplay_result()
        self.window_gobuster_result.show()
    
    def opengoresult2(self): #for database use]
        self.window_gobuster_result = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Gobuster_Result(list = self.result_gobuster_info_list)
        self.ui.setupUi(self.window_gobuster_result)
        self.ui.disaplay_result()
        self.window_gobuster_result.show()

    def show_secwindow(self):
        if Ui_MainWindow.SHOW_ATTACK_GUI == 0:
            self.window_attack_tool = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow_Attack_Tool()
            self.ui.setupUi(self.window_attack_tool, MainWindow)
            Ui_MainWindow.SHOW_ATTACK_GUI = 1
        self.window_attack_tool.show()
        MainWindow.hide()

    def extension(self):
        self.window_extension = QtWidgets.QMainWindow()
        self.ui = UI_extension_management()
        self.ui.show()
    
    def gobuster_filter_editer(self):
        self.windows_filter_editer =  QtWidgets.QMainWindow()
        self.ui = UI_gobuster_filter_list_editer()
        self.ui.show()

    def set_by_default_gobuster(self):
        if self.btn_gobuster_default.isChecked() == True:
            self.btn_gobuster_mode_dir.setChecked(True)
            self.btn_gobuster_mode_subdomain.setChecked(False)
            self.btn_gobuster_mode_vhost.setChecked(False)
            self.btn_gobuster_mode_dir.setDisabled(True)
            self.btn_gobuster_mode_subdomain.setDisabled(True)
            self.btn_gobuster_mode_vhost.setDisabled(True)
            self.btn_gobuster_dir_wordlist_filter.setDisabled(False)
            pass
        else:
            self.btn_gobuster_mode_dir.setDisabled(False)
            self.btn_gobuster_mode_subdomain.setDisabled(False)
            self.btn_gobuster_mode_vhost.setDisabled(False)
            self.btn_gobuster_dir_wordlist_filter.setDisabled(True)
        
        if self.btn_gobuster_mode_dir.isChecked() == True:
            self.btn_gobuster_dir_wordlist_filter.setDisabled(False)
        elif self.btn_gobuster_mode_dir.isChecked() == False:
            self.btn_gobuster_dir_wordlist_filter.setDisabled(True)
            pass 

    def set_by_default(self):
        #Config the Default mode setting
        if self.chk_dmode.isChecked() == True:
            self.chk_nmap_run.setChecked(True)
            self.chk_nmap_run.setDisabled(True)
            self.chk_whatweb_run.setChecked(True)
            self.chk_whatweb_run.setDisabled(True)
            self.btn_gobuster_default.setChecked(True)
            self.btn_gobuster_default.setDisabled(True)
            self.chk_gobuster_run.setChecked(True)
            self.chk_gobuster_run.setDisabled(True)
            self.frame_gobuster.setDisabled(True)
            self.chk_nikto_run.setChecked(True)
            self.chk_nikto_run.setDisabled(True)
            self.btn_gobuster_mode_dir.setChecked(True)
            self.btn_gobuster_mode_subdomain.setChecked(False)
            self.btn_gobuster_mode_vhost.setChecked(False)
            self.btn_gobuster_mode_dir.setDisabled(True)
            self.btn_gobuster_mode_subdomain.setDisabled(True)
            self.btn_gobuster_mode_vhost.setDisabled(True)
            self.btn_gobuster_dir_wordlist_filter.setDisabled(False)
        elif self.chk_dmode.isChecked() == False:
            self.chk_nmap_run.setChecked(False)
            self.chk_nmap_run.setDisabled(False)
            self.btn_gobuster_default.setDisabled(False)
            self.btn_gobuster_default.setChecked(False)
            self.chk_gobuster_run.setChecked(False)
            self.chk_gobuster_run.setDisabled(False)
            self.chk_whatweb_run.setChecked(False)
            self.chk_whatweb_run.setDisabled(False)
            self.chk_nikto_run.setChecked(False)
            self.chk_nikto_run.setDisabled(False)
            self.frame_gobuster.setDisabled(False)
            self.btn_gobuster_mode_dir.setDisabled(False)
            self.btn_gobuster_mode_subdomain.setDisabled(False)
            self.btn_gobuster_mode_vhost.setDisabled(False)
            self.btn_gobuster_dir_wordlist_filter.setDisabled(True)
        pass  
            
    def switch_user_agnet(self):
        selected = self.cmb_user_agent.currentText()
        if selected == "Safari":
            return "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
        elif selected == "Firefox":
            return "Mozilla/5.0 (Macintosh; Intel Mac OS X 13.3; rv:112.0) Gecko/20100101 Firefox/112.0"
        elif selected == "Gecko":
            return "Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko"
        elif selected == "Ramdom Normal Browser":
            return "random_normal_browser"
        elif selected == "FYP tools":
            return "FYP_tools"
        else:
            print("switch_user_agnet Error, use default user-agent")
            return "FYP_tool"
    
    def update_cmb_db(self):
        db_result= DB_connect.get_all_record_id_datetime_address() #dict 
        cmb_item_list = list()
        for item in db_result:
            cmb_item_list.append(f"{item['id']} - {item['target_address']}")
        # btn setting
        self.cmb_db.clear()
        self.btn_db_search.setDisabled(True)
        if len(cmb_item_list) != 0:
            self.cmb_db.addItems(cmb_item_list)
            self.btn_db_search.setDisabled(False)

    def result_tab_whatweb_select_url_select(self,data_list):
        selected = self.result_cmb_whatweb_url.currentText()
        selected = selected.split(" : ")[0]
        # data_list = self.whatweb_result_data_list
        select_item_data = self.whatweb_result_data_list[data_list - 1]
        self.result_lbl_whatweb_target_url_var.setText(select_item_data.get("target_url",""))
        self.result_lbl_whatweb_web_server_var.setText(select_item_data.get("web_server",""))
        self.result_lbl_whatweb_OS_var.setText(select_item_data.get("OS",""))
        version = select_item_data.get("CMS_version","")
        if version == None:
            version = "unkwon version"
        self.result_lbl_whatweb_web_technology_var.setText(f'{select_item_data.get("CMS_name","")} ({version})')
        pass

    def result_sqlmap_table_update(self):
        num_of_item = self.result_cmb_sqlmap.currentText()
        num_of_item = num_of_item.split(" : ")
        num_of_item = int(num_of_item[0])
        
        if len(self.sqlmap_all_data_list) != 0:
            select_item_dict = self.sqlmap_all_data_list[num_of_item]
            if select_item_dict['datatype'] == 'columns':
                self.result_sqlmap_table.setRowCount(len(select_item_dict['result']))
                self.result_sqlmap_table.setColumnCount(2)
                self.result_sqlmap_table.setHorizontalHeaderLabels(select_item_dict['result'].keys())
                # if "result" in select_item_dict:
                row = 0
                for key in select_item_dict['result']:
                    self.result_sqlmap_table.setItem(row,0,QTableWidgetItem(key))
                    self.result_sqlmap_table.setItem(row,1,QTableWidgetItem(select_item_dict['result'][key]))
                    row = row + 1
            elif select_item_dict['datatype'] == 'record':  
                self.result_sqlmap_table.setRowCount(len(select_item_dict['result']))
                self.result_sqlmap_table.setColumnCount(len(select_item_dict['result'][0]))
                self.result_sqlmap_table.setHorizontalHeaderLabels(select_item_dict['result'][0].keys())
                row = 0
                for item in select_item_dict['result']:
                    col = 0
                    for key in item:
                        self.result_sqlmap_table.setItem(row,col,QTableWidgetItem(item[key]))
                        col = col + 1 
                    row = row + 1


        pass
    def result_search_btn_fuct(self):
        selected_item = self.cmb_db.currentText()
        selected_item = selected_item.split(" - ",1)
        selected_item_id = selected_item[0]
        # print(selected_item_id)
        self.update_result_page(id=selected_item_id)
    
    def update_result_nikto_table(self):
        all_data_list=self.result_nikto_table_data_list 
        display_data_list = list()
        #get filter or raw data
        if len(all_data_list) != 0:
            if self.result_Nikto_chk_raw.isChecked() == True:
                for item in all_data_list:
                    if item.get("type","") == "raw":
                        if item.get("result", None) != None:
                            display_data_list.append(item['result'])
            else:
                for item in all_data_list:
                    if item.get("type","") == "filtered":
                        if item.get("result", None) != None:
                            display_data_list.append(item['result'])
        
        self.result_Nikto_table.setColumnCount(1)
        self.result_Nikto_table.setRowCount(len(display_data_list))
        self.result_Nikto_table.setColumnWidth(0, 800)
        row = 0
        for line in display_data_list:
            self.result_Nikto_table.setItem(row, 0, QTableWidgetItem(line.replace("\n","")))
            row = row + 1 

    def update_result_xsstrike(self):
        if self.xsstrike_all_data_list:
            selected_text = self.cmb_xsstrike_event_select.currentText()
            selected_text = selected_text.split(" | ",1)
            try:
                selected_number = int(selected_text[0]) - 1
            except:
                print("update_result_xsstrike Error")
            selected_data = self.xsstrike_all_data_list[selected_number]

            #updata lable and table
            self.lbl_xsstrike_cookie_info_var.setText(selected_data.get('cookie_info','not found in database'))
            if selected_data.get('result',None) != None:
                self.table_xsstrike.setColumnCount(1)
                self.table_xsstrike.setRowCount(len(selected_data['result']))
                self.table_xsstrike.setColumnWidth(0, 560)
                self.table_xsstrike.setHorizontalHeaderLabels(["possible payload"])
                row = 0
                for line in selected_data['result']:
                    self.table_xsstrike.setItem(row,0,QTableWidgetItem(line) )
                    row = row + 1
        pass

    def update_result_page(self,id=""):
        if id == "":
            try:
                id = self.current_DB_id
            except:
                print("current DB ID not found")
        result_dict = DB_connect.get_record_for_result_page(id)

        # for tab_page_number in range(1, 6): #disable page


        if len(result_dict) != 0:
            result_receivedData_exist_tools_list = result_dict.get("result_exist_tools_list","")
            self.lbl_Domain_var.setText(result_dict.get("target_url",""))
            self.lbl_datetime_var.setText(result_dict.get("date_time",""))
            self.lbl_id_var.setText(id)
            page_num_dict = {'namp':1,'whatweb':2,"gobuster":3,"nikto":4,"sqlmap":5,"xsstrike":6}
            for tool_key in page_num_dict:
                if tool_key not in result_receivedData_exist_tools_list:
                    self.result_tab.setTabEnabled(page_num_dict[tool_key],False)
            #clear whatweb_lable
            self.result_lbl_whatweb_target_url_var.setText('')
            self.result_lbl_whatweb_web_server_var.setText('')
            self.result_lbl_whatweb_OS_var.setText('')
            tools_config_dict = result_dict.get("tools_config",{})
            if len(tools_config_dict) != 0:
                ## tools config page
                self.table_result_tools_config_info.setRowCount(len(tools_config_dict))
                self.table_result_tools_config_info.setColumnCount(3)
                self.table_result_tools_config_info.setHorizontalHeaderLabels(['Tools','Status','Other'])
                self.table_result_tools_config_info.setColumnWidth(2,250)
                x = 0
                for line in tools_config_dict:
                    self.table_result_tools_config_info.setItem(x,0,QTableWidgetItem(line))
                    if tools_config_dict[line].get("open") == 1:
                        status = "enable"
                    elif tools_config_dict[line].get("open") == 0:
                        status = "disable"
                    else:
                        status = "unkwon"
                    self.table_result_tools_config_info.setItem(x,1,QTableWidgetItem(status))
                    
                    other_info = ""
                    for data_key in tools_config_dict[line]:
                        if data_key != "open":
                            other_info = other_info + f"'{data_key}'={tools_config_dict[line][data_key]}"

                    self.table_result_tools_config_info.setItem(x,2,QTableWidgetItem(other_info))
                    x = x+1
            # print(result_dict)
            if "nmap" in result_receivedData_exist_tools_list:
                self.result_tab.setTabEnabled(1,True) #enable tab
                data_list = DB_connect.get_one_tool_result(id=id,tool_name="nmap")
                
                if len(data_list) != 0:
                    key_list = list()
                    for key in data_list[0]:
                        if key != "tools":
                            key_list.append(key)
                    self.table_result_namp_info.setRowCount(len(data_list))
                    self.table_result_namp_info.setColumnCount(len(data_list[0])-1)
                    self.table_result_namp_info.setHorizontalHeaderLabels(key_list)
                    self.table_result_namp_info.setColumnWidth(0,160)
                    x = 0
                    for item in data_list:
                        y = 0
                        for key in item:
                            if key != "tools":
                                self.table_result_namp_info.setItem(x,y,QTableWidgetItem(item[key]))
                                y = y+1
                        x = x + 1
                # print(data_list)
                pass
            if "whatweb" in result_receivedData_exist_tools_list:
                self.result_tab.setTabEnabled(2,True)
                self.whatweb_result_data_list = DB_connect.get_one_tool_result(id=id,tool_name="whatweb")
                num_of_item = 1
                self.result_cmb_whatweb_url.clear()
                for item in self.whatweb_result_data_list:
                    self.result_cmb_whatweb_url.addItem(f"{num_of_item} : {item.get('target_url')}")
                self.result_btn_whatweb_display.clicked.connect(self.result_tab_whatweb_select_url_select)
                pass
            if "gobuster" in result_receivedData_exist_tools_list:
                self.result_btn_gobuster_open_page.hide()
                self.result_btn_gobuster_open_page.setDisabled(True)
                self.result_tab.setTabEnabled(3,True)
                gobuster_list = DB_connect.get_one_tool_result(id=id,tool_name="gobuster")
                if len(gobuster_list) != 0 :
                    self.result_lbl_gobuster_mode_var.setText(gobuster_list[0].get('mode',"unkwon"))
                    self.result_lbl_gobuster_wordlist_var.setText(gobuster_list[0].get('used_wordlist',"unkwon"))
                    self.result_gobuster_info_list = gobuster_list
                    if self.result_lbl_gobuster_mode_var.text() == "dir":
                        self.result_lbl_gobuster_dir_result_len.show()
                        self.result_lbl_gobuster_dir_result_len_var.show()
                        self.result_lbl_gobuster_dir_result_len_var.setText(f"{len(gobuster_list)}")
                        self.result_btn_gobuster_open_page.show()
                        self.result_btn_gobuster_open_page.setDisabled(False)
                        self.result_table_gobuster.hide()
                        self.result_btn_gobuster_open_page.clicked.connect(self.opengoresult2)
                    elif self.result_lbl_gobuster_mode_var.text() == "subdomain":
                        self.result_lbl_gobuster_dir_result_len.hide()
                        self.result_lbl_gobuster_dir_result_len_var.hide()
                        self.result_btn_gobuster_open_page.setDisabled(True)
                        self.result_btn_gobuster_open_page.hide()
                        #diplay table
                        self.result_table_gobuster.show()
                        self.result_table_gobuster.setColumnCount(1)
                        self.result_table_gobuster.setRowCount(len(gobuster_list))
                        self.result_table_gobuster.setHorizontalHeaderLabels(['subdomain'])
                        self.table_result_namp_info.setColumnWidth(0,500)
                        row = 0
                        for line in gobuster_list:
                            if line.get("subdomain",None) != None:
                                self.result_table_gobuster.setItem(row,0,QTableWidgetItem(line["subdomain"]))
                                row = row + 1
                    elif self.result_lbl_gobuster_mode_var.text() == "vhost" :
                        self.result_lbl_gobuster_dir_result_len.hide()
                        self.result_lbl_gobuster_dir_result_len_var.hide()
                        self.result_btn_gobuster_open_page.setDisabled(True)
                        self.result_btn_gobuster_open_page.hide()
                        self.result_table_gobuster.show()
                        self.result_table_gobuster.show()
                        self.result_table_gobuster.setColumnCount(1)
                        self.result_table_gobuster.setRowCount(len(gobuster_list))
                        self.result_table_gobuster.setHorizontalHeaderLabels(['vhost'])
                        
                        row = 0
                        for line in gobuster_list:
                            if line.get("vhost",None) != None:
                                self.result_table_gobuster.setItem(row,0,QTableWidgetItem(line["vhost"]))
                                row = row + 1
                        self.table_result_namp_info.setColumnWidth(0,500)
                        #display table


                        pass
                pass

            if "nikto" in result_receivedData_exist_tools_list:
                self.result_tab.setTabEnabled(4,True)
                self.result_nikto_table_data_list = DB_connect.get_one_tool_result(id=id,tool_name="nikto")
                # self.result_Nikto_chk_raw.setChecked(True)
                self.update_result_nikto_table()
                pass
            
            if "sqlmap" in result_receivedData_exist_tools_list:
                self.result_tab.setTabEnabled(5,True)
                self.sqlmap_all_data_list = DB_connect.get_one_tool_result(id=id,tool_name="sqlmap")
                self.result_cmb_sqlmap.clear()
                line = 0
                for item in self.sqlmap_all_data_list:
                    self.result_cmb_sqlmap.addItem(f"{line} : URL:{item['target_url']}  Database:{item.get('database','N/A')}  Table:{item.get('table','N/A')}  Type:{item['datatype']}")
                    line = line + 1
                    pass
            
            if "xsstrike" in result_receivedData_exist_tools_list:
                self.result_tab.setTabEnabled(6,True)
                self.xsstrike_all_data_list = DB_connect.get_one_tool_result(id=id,tool_name="xsstrike")
                if self.xsstrike_all_data_list:
                    num_of_data = 1
                    self.cmb_xsstrike_event_select.clear()
                    for data in self.xsstrike_all_data_list:
                        if data.get("target_url",None) != None:
                            self.cmb_xsstrike_event_select.addItem(f"{num_of_data} | {data['target_url']}")
                            num_of_data = num_of_data + 1
                self.btn_xsstrike_select.clicked.connect(self.update_result_xsstrike)
                pass
            
    
if __name__ == "__main__":

    #def call_GUI():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    pass